### ISSUE TITLE
CDM component in LambdaCDM universe

### ISSUE THREAD

**Issue by lemiche** [lesgourg/class_public#101]
Hi,

I attach here a plot, where I show the ratio of the transfer functions of
the CDM component in a simple LambdaCDM universe at different times, taking its growth factor into account, where in a LambdaCDM universe the linear growth factor should in principle have NO k dependence. The plot shows that the ratio differs from 1varying across the k range, say of k=10^-3 to k=10^-1 by more than 1%, say 1.5%.

Could you please explain this unexpected k dependence, which deviates from the usual high precision standard expectation (1%)?

This deviation exactly entails a corresponding deviation of more than the 1% desirable accuracy in the results which I am interested at, and that is why it is important to me to be able to explain this additional k dependence.

Thanks! 

![classinquiry](https://cloud.githubusercontent.com/assets/11328288/15269884/56179462-1a0d-11e6-9886-bcfde6cc6622.jpeg)

**Comment by ThomasTram** [comment]
Hi

This scale-dependence of the growth at large scales is due to radiation. This was noticed in two previous issues, https://github.com/lesgourg/class_public/issues/95 and https://github.com/lesgourg/class_public/issues/71.

Cheers,
Thomas Tram
