### ISSUE TITLE
Extracting Source functions from transfer.c

### ISSUE THREAD

**Issue by daanmeerburg** [lesgourg/class_public#104]
I am trying to extract the source functions from transfer.c. I have added the following lines in transfer.c:

`// JM 2016
  FILE \* out=fopen("/mnt/raid-cita/meerburg/data/Sources_h_T.txt","w");
  FILE \* out2=fopen("/mnt/raid-cita/meerburg/data/Sources_h_P.txt", "w");
  FILE \* out3=fopen("/mnt/raid-cita/meerburg/data/Sources_z_P.txt", "w");
  FILE \* out4=fopen("/mnt/raid-cita/meerburg/data/Sources_z_T.txt", "w");

  for (index_md = 0; index_md < ptr->md_size; index_md++) {

```
class_alloc(sources[index_md],
            ppt->ic_size[index_md]*ppt->tp_size[index_md]*sizeof(double*),
            ptr->error_message);

for (index_ic = 0; index_ic < ppt->ic_size[index_md]; index_ic++) {

  for (index_tp = 0; index_tp < ppt->tp_size[index_md]; index_tp++) {

    if ((pnl->method != nl_none) && (_scalars_) &&
        (((ppt->has_source_delta_m == _TRUE_) && (index_tp == ppt->index_tp_delta_m)) ||
         ((ppt->has_source_theta_m == _TRUE_) && (index_tp == ppt->index_tp_theta_m)) ||
         ((ppt->has_source_phi == _TRUE_) && (index_tp == ppt->index_tp_phi)) ||
         ((ppt->has_source_phi_prime == _TRUE_) && (index_tp == ppt->index_tp_phi_prime)) ||
         ((ppt->has_source_phi_plus_psi == _TRUE_) && (index_tp == ppt->index_tp_phi_plus_psi)) ||
         ((ppt->has_source_psi == _TRUE_) && (index_tp == ppt->index_tp_psi)))) {

      class_alloc(sources[index_md][index_ic * ppt->tp_size[index_md] + index_tp],
                  ppt->k_size[index_md]*ppt->tau_size*sizeof(double),
                  ptr->error_message);

      for (index_tau=0; index_tau<ppt->tau_size; index_tau++) {
        for (index_k=0; index_k<ppt->k_size[index_md]; index_k++) {
          sources[index_md]
            [index_ic * ppt->tp_size[index_md] + index_tp]
            [index_tau * ppt->k_size[index_md] + index_k] =
            ppt->sources[index_md]
            [index_ic * ppt->tp_size[index_md] + index_tp]
            [index_tau * ppt->k_size[index_md] + index_k]
            * pnl->nl_corr_density[index_tau * ppt->k_size[index_md] + index_k];

        }
      }
    }
    else {
      sources[index_md][index_ic * ppt->tp_size[index_md] + index_tp] =
        ppt->sources[index_md][index_ic * ppt->tp_size[index_md] + index_tp];
                            printf("got here 2 %li %li \n", index_md, index_tp);
                for (index_tau=0; index_tau<ppt->tau_size; index_tau++) {
        for (index_k=0; index_k<ppt->k_size[index_md]; index_k++) {
```

// JM 2016
                                if ((index_md == ppt->index_md_tensors) && (index_tp == ppt->index_tp_p)) { 
                                    fprintf(out2,"%le %le %le\n",ppt->tau_sampling[index_tau],ppt->k[0][index_k],sources[index_md][index_ic \* ppt->tp_size[index_md] + index_tp][index_tau \* ppt->k_size[index_md] + index_k]);
                                }
                                if ((index_md == ppt->index_md_tensors) && (index_tp == ppt->index_tp_t2)) { 
                                    fprintf(out,"%le %le %le\n",ppt->tau_sampling[index_tau],ppt->k[0][index_k],sources[index_md][index_ic \* ppt->tp_size[index_md] + index_tp][index_tau \* ppt->k_size[index_md] + index_k]);
                                }
                                if ((index_md == ppt->index_md_scalars) && (index_tp == ppt->index_tp_p)) { 
                                    fprintf(out3,"%le %le %le\n",ppt->tau_sampling[index_tau],ppt->k[0][index_k],sources[index_md][index_ic \* ppt->tp_size[index_md] + index_tp][index_tau \* ppt->k_size[index_md] + index_k]);
                                }
                                                                if ((index_md == ppt->index_md_scalars) && (index_tp == ptr->index_tt_t2)) {
                                                                fprintf(out4,"%le %le %le\n",ppt->tau_sampling[index_tau],ppt->k[0][index_k],sources[index_md][index_ic \* ppt->tp_size[index_md] + index_tp][index_tau \* ppt->k_size[index_md] + index_k]);
                                }
                            }
                        }

```
    }
  }
}
```

  }
  fclose(out);
  fclose(out2);
  fclose(out3);
  fclose(out4);
  return _SUCCESS_;`

I am using these files to generate the flat sky transfer functions. They give me a result that is almost correct for BB (not quite on large scales) and some factor of 16, they give me a correct results for EE (from scalars) up to an exact factor of 2.7, they give me an totally wrong spectrum for TT. 

The factors I can deal with (although I would really like to understand them), but the TT spectrum is strange. I can get the right results with CAMB, but unfortunately CAMB has a different handling of the B-mode tensors source function which only works correctly for power spectra (and not for higher order correlation functions). 

I hope you can help identifying the problem

Thanks in advance

Daan

**Comment by ThomasTram** [comment]
Hi Daan,

what is the formula for the line-of-sight integral you are using? There is probably a mismatch between what you expect the source function to be and what it actually is. The formulae used in CLASS are given by equations (2.37)-(2.39) in http://arxiv.org/pdf/1305.3261.pdf, although for the scalar perturbations some integrations by parts are performed (cf. Appendix A of http://arxiv.org/pdf/1312.2697.pdf). 

Cheers,
Thomas

**Comment by daanmeerburg** [comment]
Hi Thomas

The question is what am I printing when I write:

								if ((index_md == ppt->index_md_tensors) && (index_tp == ppt->index_tp_p)) { 
									fprintf(out2,"%le %le %le\n",ppt->tau_sampling[index_tau],ppt->k[0][index_k],sources[index_md][index_ic * ppt->tp_size[index_md] + index_tp][index_tau * ppt->k_size[index_md] + index_k]);

Is this everything inside the integral of Eq. 2.39 or just part of it. I am asking since I do believe that my flat sky results are so close to what they should be for B and E. 

Thanks
Daan

**Comment by ThomasTram** [comment]
Hi again

The source function that you store is everything inside the integral in eqs. (2.37-2.39) except for the radial function (phi, epsilon or beta). The tensor temperature source is the same as eq 3.86 in Maresuke's thesis S_I^{(T)}. Our line-of-sight integral for the tensor temperature is also the same as his equation 3.101except for a factor sqrt(3/8). But this factor is probably related to how he defines the normal mode expansion.

I think you should first of all see if you can reproduce the non-flat sky result by manually convolving the temperature source that you extract with the radial function (i.e., j_l(x)/x^2 where x=k(tau0-tau) ). Once you match the result of CLASS, try to apply his formula.

Cheers,
Thomas
