### ISSUE TITLE
Access growth factor through CLASS' Python wrapper

### ISSUE THREAD

**Issue by fkoehlin** [lesgourg/class_public#105]
Dear CLASS developers,

Is it possible to access the linear growth factor (normalized to unity today) as a function of redshift from CLASS' Python wrapper? I haven't looked into the C source code yet but I'm assuming that there must exist a function for the linear growth factor.

Any help with that is highly appreciated!

Cheers,

Fabian

**Comment by borisbolliet** [comment]
Dear Fabian,

Indeed there is a simple way to do this.

In order to access the value of the linear growth factor at a given redshift you need to use the following lines. Say you want the linear growth factor at  redshift = 0.8:
```

  double redshift = 0.8

  double tau;
  int first_index_back = 0;
  
  double * pvecback;
  class_alloc(pvecback, pba->bg_size*sizeof(double),pba->error_message);


class_call(background_tau_of_z(pba, redshift, &tau),
           pba->error_message,
           pba->error_message);


class_call(background_at_tau(pba,
                             tau,
                             pba->long_info,
                             pba->inter_normal,
                             &first_index_back,
                             pvecback),
           pba->error_message,
           pba->error_message);

   linear_growth_factor_at_z = pvecback[pba->index_bg_D]
```
Let me know if you need further clarification,

Kind regards,

Boris

**Comment by fkoehlin** [comment]
Hi Boris,

Thanks for your super-fast answer! Indeed if you could clarify/ expand a bit more on how to propagate these lines then to "classy.pyx" so that I can call it from Python, that would be very helpful. 
Do I just have to define a new function in "classy.pyx" and plug your lines (modified accordingly) in there (e.g. following the outline for the function "z_of_r")?

Cheers,

Fabian

**Comment by borisbolliet** [comment]
You do not need to define a new function in classy.pyx, because normally you can always access the growth factor via (see my updated first comment):

`cosmo.get_background()['gr.fac. D']`

If you really want to define a new function specific to the growth factor, then do:
In classy.pyx:


    def growth_factor_at_z(self, z):
        """
        D(z)

        Return the growth factor (exactly, the quantity defined by Class as index_bg_D
        in the background module)

        Parameters
        ----------
        z : float
                Desired redshift
        """
        cdef double tau
        cdef int last_index #junk
        cdef double * pvecback

        pvecback = <double*> calloc(self.ba.bg_size,sizeof(double))

        if background_tau_of_z(&self.ba,z,&tau)==_FAILURE_:
            raise CosmoSevereError(self.ba.error_message)

        if background_at_tau(&self.ba,tau,self.ba.long_info,self.ba.inter_normal,&last_index,pvecback)==_FAILURE_:
            raise CosmoSevereError(self.ba.error_message)

        H = pvecback[self.ba.index_bg_D]

        free(pvecback)

        return H





And add the following line (` int index_bg_D`) in cclassy.pxd:

    cdef struct background:
        ErrorMsg error_message
        int bg_size
        int index_bg_ang_distance
        int index_bg_lum_distance
        int index_bg_conf_distance
        int index_bg_H
        int index_bg_D
        ...

**Comment by fkoehlin** [comment]
Thanks a lot! I'll try the solution in your updated answer first.
But thanks for the very detailed example of how to define it also anew in classy.pyx (following the outline of "z_of_r" in there I think I would have almost managed to write it myself, too, but I would have forgotten about the changes in cclassy.pxd...)!

Cheers, 

Fabian

**Comment by miguelzuma** [comment]
Just a quick cautionary comment: the growth factor computed in the background module is just an approximation valid in a matter-only universe. The following is the definition from background.c, line 1596

    /* D = H \int [da/(aH)^3] = H \int [dtau/(aH^2)] = H * growth */
    pvecback[pba->index_bg_D] = pvecback[pba->index_bg_H]*pData[i*pba->bi_size+pba->index_bi_growth];

If you want to consider more general situations you'll need to obtain information from the perturbations module (which is where delta_cdm(k, tau) is computed).

**Comment by amoradinejad** [comment]
Hi Miguel, 
Following your explanation on growth, is there a function in perturbation module that returns the scale-dependant growth D(k,z) and f(k,z) = dlnD/dlna (for example in the cosmology with massive neutrinos)?
