### ISSUE TITLE
Changing value of q_size_ncdm

### ISSUE THREAD

**Issue by bhorowitz** [lesgourg/class_public#110]
Perhaps I haven't been looking closely enough at the code, but is there currently a way to change the size of the q_ncdm list for different non-cold dark matter species. It isn't entirely clear to me where these numbers are set and how to change them within the code.

**Comment by ThomasTram** [comment]
Hi

The list of q-values (size and values) are computed automatically by the code based on the ````tol_ncdm_synchronous```` and ````tol_ncdm_newtonian```` (depending on the gauge). The background is handled by ````tol_ncdm_bg````. The strategy for selecting q-values is described in detail in the paper http://arxiv.org/pdf/1104.2935.pdf, in particular section 2.2.

Cheers,
Thomas
