### ISSUE TITLE
Units of q in ncdm perturbation code

### ISSUE THREAD

**Issue by bhorowitz** [lesgourg/class_public#116]
What are the units of q in the perturbation code? In the documentation I see that q in the transfer function code is in units of comoving angular diameter distance to recombination, but is that also used in the perturbation codes Boltzmann equations? It doesn't seem to be specified anywhere.

**Comment by bhorowitz** [comment]
Judging by the epsilon term (epsilon = sqrt(q*q+a2*pba->M_ncdm[n_ncdm]*pba->M_ncdm[n_ncdm])) it seems like it has units of a*M_ncdm which are both dimensionless; so q is also dimensionless.

**Comment by ThomasTram** [comment]
Hi

Our q is defined in the [CLASS IV paper](https://arxiv.org/pdf/1104.2935.pdf) in terms of the q used in the Ma&Bertschinger [paper](http://arxiv.org/pdf/astro-ph/9506072.pdf).

Cheers,
Thomas
