### ISSUE TITLE
Strange Gaussian result  vs weighted Dirac windows & Non-Limber

### ISSUE THREAD

**Issue by jean-eric** [lesgourg/class_public#117]
Well,
I am a CLASSgal user and I'm facing a problem concerning the computation of Cl (only the matter density effect) using a Gaussian window (mean = 1, sigma=0.03, cut at 5sigma). When I compare the results with DIrac window in the range z in [0.85, 1.15] and ell<500 and k_scalar_max_tau0_over_l_max=3, with in the same conditions but the Gaussian window pre-cited, it comes out that the Gaussian window result in largely smaller then the set of Dirac results. I spent a lot of times changing some parameters concerning the Bessel sampling and so on (note that in all cases I run with l_switch_limber = 10000 & l_switch_limber_for_cl_density_over_z = 10000. ) but the above strange result is stable. 

So, does some one can tell me why a weighted means of Dirac results is not equivalent to the Gaussian result ? 

It is illustrated in the figure.
![capture d ecran 2016-09-22 a 11 26 34](https://cloud.githubusercontent.com/assets/9536377/18743035/728263c8-80b7-11e6-90a3-b89761b658de.png)

Thanks. Jean-Eric

**Comment by jean-eric** [comment]
Ok, sorry for this issue which is a physical meaning ;) In a thick redshift band one experiences not only the auto-correlation of some discretized Dirac-like sub-shells but also all their inter-cross-correlation contributions which tends to washout the contrast. Good ! I feel less stupid.

**Comment by ThomasTram** [comment]
Thanks a lot for sharing your solution!
