### ISSUE TITLE
Compatibility with intel python

### ISSUE THREAD

**Issue by whqnrjs** [lesgourg/class_public#118]
Hi,
I'm currently trying to run the CLASS python wrapper with intel python.
Making the CLASS is succeed, but importing the classy is troubling.
(I compiled the CLASS code with the latest version of icc, and the version of intel python is beta.)

Python 2.7.11 (default, Jun  2 2016, 16:21:40) 
[GCC Intel(R) C++ gcc 4.8 mode] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from classy import Class
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/angelvisean/.local/lib/python2.7/site-packages/classy.so: undefined symbol: __kmpc_end_serialized_parallel

I think that this issue is related to the icc, but I can't resolve this problem.
Is there any good idea to make the intel python work?

**Comment by ThomasTram** [comment]
Hi

One solution is of course to just use gcc. I don't think there are any advantages (performance or otherwise) of using icc compared to gcc. However, if you really want to use icc, have a look in this post:
https://github.com/lesgourg/class_public/issues/40

Cheers,
Thomas Tram
