### ISSUE TITLE
Output: Time evolution

### ISSUE THREAD

**Issue by tomatinhos** [lesgourg/class_public#119]
Hi,

What would be the best way to tell the code to give as output the time evolution of a given quantity, e.g. the growth rate of matter perturbations.

Thank you,

João

**Comment by ThomasTram** [comment]
Hi

If you are interested in the Newtonian growth rate which is a background quantity, just use ````write background = yes```` in the .ini file or use ````get_background()```` from the Python wrapper. If you are interested in actual perturbations, use for instance  ````k_output_values = 0.01, 0.1, 1.0```` as explained in ````explanatory.ini````. The perturbations can be accessed from the Python wrapper through ````get_perturbations()````. In either case, if the quantity you want is not implemented, you must add a few lines to the code in (some of) the functions ````background_output_titles()````, ````background_output_data````, ````perturb_prepare_output()````, ````perturb_print_variables()````. It should be fairly self-explanatory if you look in these functions.

Cheers,
Thomas
