### ISSUE TITLE
dNdz_selection: analytic case

### ISSUE THREAD

**Issue by jean-eric** [lesgourg/class_public#120]
Hello,

In the reference arXiv:1307.1459v4 Eq.3.1, it is stated that one uses
dN/dz ~ (z/0.55)^2 exp[-(z/0.55)^2]
inspired from DES survey.
But
1) in the code "transfer.c" the function coded as "analitic" option is
dN/dz ~ (z/0.55)^2 exp[-(z/0.55)^1.5]
2) I do not find the DES reference in the quoted web site.

=> Does one can tell me which analitic function have been used for the paper?

Thanks
JE

**Comment by montanari** [comment]
Hi,

It looks like a typo in the paper. Looking at the [code version ](http://cosmology.unige.ch/content/classgal) used in that paper, the exponent 1.5 was considered. This is consistent e.g. with eq. 1 of [this other paper](https://arxiv.org/pdf/1207.6487.pdf).

Francesco

**Comment by jean-eric** [comment]
Thanks.JE
