### ISSUE TITLE
Gaussian window parameters

### ISSUE THREAD

**Issue by jean-eric** [lesgourg/class_public#121]
Hello
In initial file one uses for instance:
...
selection=gaussian
selection_mean=1.00
selection_width=0.03
selection_cut_at_sigma=5
non_diagonal=0
...
To get a Gaussian selection function N(mean,sigma). I have verified in transfer.c that the "selection_width" is in place of a "sigma". So far so good.

But in reference arXiv:1307.1459v4, in many places it is stated : "Results are computed for a Gaussian bin centered around z=0.55 and with half-width Dz = 0.1".

1) Is there a typo or not, as if it is really a Gaussian half-width of Dz=0.1 then the sigma = Dz/1.18 ~0.085 ?
2) Does one know also what was the selection_cut_at_sigma used ??? (5 is de default by the way in the code)?

Thanks
Jean-Eric

**Comment by montanari** [comment]
1) It refers to the sigma of the Gaussian, i.e., `selection_width=0.1`. From the `explanatory.ini`:
> The width stands for one standard deviation of the gaussian
>     (in z space), or for the half-width of the top-hat.

2) Default value.

Best,
Francesco

**Comment by jean-eric** [comment]
Yes. as I have read this file ;) But then there is a typo in the paper if it is mentionned that Dz=0.1 is the half width of the Gaussian selection function.
Thanks
JE

**Comment by montanari** [comment]
By half-width of the Gaussian we meant sigma (by analogy with the tophat binning case; in other words Dz of the paper is selection_width of the code), so I don't think there is a typo as long as this is used consistently throughout the paper.

Best,
Francesco

**Comment by jean-eric** [comment]
Ok thanks Francesco.
