### ISSUE TITLE
Classy: How to change k & Pk output units.

### ISSUE THREAD

**Issue by utkarshgiri** [lesgourg/class_public#125]
Hi,

How do I get my outputs for k and Pk in the units of Mpc{-1} and Mpc^3 using the python wrapper. 

Thank you!

**Comment by ThomasTram** [comment]
k and P(k) are already in these units, so no need to change anything. If you want to convert into h/Mpc units, you can get ````h```` by calling ````.h()````

Cheers,

Thomas Tram

**Comment by utkarshgiri** [comment]
Thank you so much.
