### ISSUE TITLE
exercise pdfs for CLASS tutorials?

### ISSUE THREAD

**Issue by davidrcurtin** [lesgourg/class_public#127]
Dear Julien and Thomas,

we're trying to learn how to use your CLASS code, and have been working our way through your tutorial slides 
https://lesgourg.web.cern.ch/lesgourg/class-tour/class-tour.html
We're greatly enjoying the tutorials and learning how to use the code. It'll be very helpful for our research. Thank you for putting so much work into this! 

We wanted to ask whether you had pdfs of the exercises available? We only have the first one (exercises 0 to 2b), and we know there are more exercises in later tutorials. (Of course, the exercises are also in the slides, but the worksheet PDFs have more information that's very helpful to complete the exercises.) 

Thank you very much for your help,

Best,

David

**Comment by ThomasTram** [comment]
Hi

Thanks for your nice words. Here are all the CLASS exercises I could dig up on my laptop:
[exercises.pdf](https://github.com/lesgourg/class_public/files/608428/exercises.pdf)
[CLASS_Python.pdf](https://github.com/lesgourg/class_public/files/608438/CLASS_Python.pdf)
The second is a small lecture focused on the Python wrapper but with a few exercises as well. This is a little bit outdated, so let me point out that 
* ````.cleanup()```` should not be called, it may not even exist any more.
* Inline SVG format can now be set using the magic command: ````%config InlineBackend.figure_format = 'svg'```` so no real need to make an alias anymore.

Cheers,
Thomas

**Comment by davidrcurtin** [comment]
Thank you Thomas!
