### ISSUE TITLE
problem with mkl installation

### ISSUE THREAD

**Issue by mahtaparsa** [lesgourg/class_public#129]
Dear all,
Hi and thanks for your guidance.I have modified the CLASS code for my cosmological model, and now I want to use montepython in order to compare my model with the Planck data. I have downloaded the plc-2.0 file from Planck legacy archive (> cosmology products > likelihood), and put it in a file with the modified CLASS code and the montepython code. However, I have problem with installing the mkl, and when I execute './waf configure --install_all_deps --mkl' in the plc-2.0 folder, the error 'waf: error: no such option: --mkl' would appear. And therefore, the configuration will fail. Please guide me in order to solve this problem.

**Comment by ardok-m** [comment]
From plc-2.0/readme.md 

> ##### Linux with mkl
> 
> Use the following instructions to install on a Linux machine with ifort and
> mkl, letting the tool install all the optional prerequisites.  The mkl library
> is available on the computer at the path ``$MKLROOT`` and its version is >=10.3 
> (probably the case if your mkl library is post 2011).  The C compiler will be 
> either gcc or clang (tested in that order). The C compiler will be either gcc, 
> icc or clang (tested in that order).  The Fortran compiler will be eiher ifort
> or gfortran (tested in that order).  Installation will be performed in the
> current plc directory.
> ```
> ./waf configure --install_all_deps --lapack_mkl=$MKLROOT
> ./waf install
> ```

Note that $MKLROOT is the path for mkl if it is installed, otherwise is empty.

**Comment by mahtaparsa** [comment]
Dear ardok-m,
Thanks for your reply. My problem about configuration solved by executing './waf configure' and your suggestion './waf configure --install_all_deps --lapack_mkl=$MKLROOT' will work too. However, now I have problem with './waf install' in which I have 'Build failed' and 'AttributeError: sig' errors. Do you have any suggestion about this problem?
Best
