### ISSUE TITLE
problem with python wrapper on fedora

### ISSUE THREAD

**Issue by mahtaparsa** [lesgourg/class_public#133]
Hi everybody,
I am using fedora distribution for modifying CLASS. And I have problem with installing python wrapper, that when in CLASS directory I execute : $ python -c "from classy import Class" , this error would appear:
File "<string>" ,line 1, in <module>
ImportError : /home/.../.local/lib/python2.7/site-packages/classy.so : undefined symbol : _ZGVbN2v_sin

It is worth to say that, in ubuntu distribution there is no problem with installing the python wrapper.
Please guide me how to install python wrapper on fedora.I need it for using montepython. 
Thanks

**Comment by montanari** [comment]
Hi,

I recently had a similar issue (I guess it may be related to some update to cython or gcc). I solved by changing optimization flag in the Makefile to `OPTFLAG = -O3` for strict standards compliance when using classy.

Best,
Francesco

**Comment by ThomasTram** [comment]
Hi

This issue has been raised and answered before:
https://github.com/lesgourg/class_public/issues/99

Cheers,
Thomas

**Comment by mahtaparsa** [comment]
Dear montanari and Thomas,
Thanks for your replies. Unfortunately your suggestions did not work. 
It is surprising that in $python , there is no complain with writing  >>>import Classy , however writing  >>>import classy , would result in the error:  
File "<string>", line 1, in <module>
ImportError: /home/.../.local/lib/python2.7/site-packages/classy.so: undefined symbol: _ZGVbN2v_sin

Any more suggestions for solving the problem?
(It seems that python wrapper does not work in fedora distribution).

**Comment by ThomasTram** [comment]
Hi

Did you compile the test program I wrote in the previous issue? And compile it using the flags I wrote? Did it execute without any problem? The undefined symbol is exactly the sine function from the mvec library, so I would be very surprised if this is not the same issue..

Cheers,
Thomas

**Comment by mahtaparsa** [comment]
Dear Thomas,
I made the testmvec.c file as you described in the previous issue and put that file in the CLASS folder or in the python folder. Then I execute "gcc testmvec.c -O1 -ftree-loop-vectorize -ffast-math -lm -mavx" in the testmvec.c directory and then I execute "gcc testmvec.c -O1 -ftree-loop-vectorize -ffast-math -lmvec -lm -mavx" , that there was no complain after compiling. I also modified the setup.py with "libraries=["class","mvec","m"]" and then tried to import classy in python. However the same error was appeared and it did not work. 
Best

**Comment by ThomasTram** [comment]
Hi, you need to *run* the code (a.out) after compiling. There is no compile error, but when you execute the programme there should be a missing symbol error.

**Comment by mahtaparsa** [comment]
sorry for asking this question. but how should I run the a.out code?

**Comment by mahtaparsa** [comment]
Dear Thomas,
after running the a.out code with executing  $./a.out  , there was no complaining. And when I executed "from classy import Class" in python, the same error (undefined symbol) appeared. So it did not solve the problem.

**Comment by ardok-m** [comment]
I don't find any error with the testmvec.c program. Nevertheless, I do in classy if I don't use ``libraries=["class","mvec","m"]``.

Just in case, @mahtaparsa, did you compile classy after adding those libraries to setup.py? It is not clear in your message and it seems you imported classy without recompiling it.

**Comment by mahtaparsa** [comment]
Dear ardok-m,
Thanks for your reply. I think, I added the libraries after compiling and then imported classy, which resulted in the mentioned error.

**Comment by ardok-m** [comment]
You need to recompile classy any time you modify it in order to get the new changes.
