### ISSUE TITLE
Set number of threads for openmp

### ISSUE THREAD

**Issue by borisbolliet** [lesgourg/class_public#135]
Dear All,
I am compiling CLASS with openmp.
What is the way to set the number of threads CLASS can use? 
(I am not talking about mpirun -np, but about the number of threads used by each copy of CLASS)
Thank you very much,
Boris

**Comment by ThomasTram** [comment]
You can set the environment variable:
````
export OMP_NUM_THREADS=4
````
Note that if you run on a cluster, you should make sure that this parameter is also set on the individual nodes executing CLASS. Normally, if you set this variable in your jobscript, the environment variables are carried over to the nodes.

Cheers,
Thomas

**Comment by borisbolliet** [comment]
Thank you very much for this information,
Kind Regards,
Boris
