### ISSUE TITLE
class_call in OMP

### ISSUE THREAD

**Issue by DanBThomas** [lesgourg/class_public#144]
Hi guys

Quick question:
Is it possible to use class calls in an openmp "parallel for" section?
I'm getting compiler errors for class_call(array_spline...) and class_call(array_integrate_all_spline...).
(Each iteration of the loop involves performing an integral).

Thanks
Dan

**Comment by lesgourg** [comment]
Yes, sure, there should be no problem if things are done properly (declaration of private/public variables etc...) There is an example in the main that you find in test/test_loops_omp.c. I added this file because somebody had the same question a couple of years ago. There, Class is called inside an openmp "for" loop, while each instance of Class is also openmp parallelised. So this shows that there is no issue with two layers of parallelisation and that Class is thread-safe. I hope this helps.

**Comment by lesgourg** [comment]
Sorry I misunderstood your question! What you want is to modify the code internally and add new parallelised loops inside Class. In that case you are right: you cannot use the same usual macros (class_call, class_alloc...) inside the parallel zone; but we have also defined specific macros for these zones, already used in specific zones of the code. I will send you more details very soon within this discussion.

**Comment by lesgourg** [comment]
So here is the more specific answer: include/common.h defines the macros
class_call_parallel(...)
class_alloc_parallel(...)
class_test_parallel(...)
which should be used in replacement of class_call, class_alloc and class_test inside openMP parallel zones. The best way to check how they work and differ from the other ones is to look at explicit examples that you find inside source/perturbations.c, transfer.c and spectra.c. The reason for which these functions exist is that the way to exit from an openMP loop in case some function returns a _FAILURE_ cannot be the usual one (this is why you got compiler errors with your first try). As you will see inside the examples, around the parallel zone, you need to define a boolean variable "abort", which value will be updated automatically by the parallel-specific macros. This is actually the only difference. Just grep for "abort" in the above examples, and you'll get it easily.

**Comment by lesgourg** [comment]
Hi Dan, Did I address your comment in the last message? May I close this issue?

**Comment by DanBThomas** [comment]
Sorry, it has been a crazy week.
Your response was brilliant, thank you.

I have now parallelised my addition to CLASS and it all works :-)
