### ISSUE TITLE
How to increase Background precison?

### ISSUE THREAD

**Issue by mirandawelber** [lesgourg/class_public#146]
Dear all, 

Maybe a simple question, but i couldn't solve on my own. 

 I wish to increase precision of background integration. Now it is up to 5000 points for each variable. I wish to increase maybe up to 50000. How to do that?  

Thanks in advance,

**Comment by lesgourg** [comment]
Hi Miranda, 
Let's not confuse two things:
* the actual precision of the integration
* the number of points stored in memory and written in a file when you pass "write background = yes"

Each of the two is governed by one precision parameter:
* for the actual precision, the relevant precision parameter is tol_background_integration set by default to 1.e-2. You can make it smaller by passing e.g. in your input file:

tol_background_integration = 1.e-4

but it will have no effect on the number of points which are stored or written.
* for the number of values stored/written, the relevant precision parameter is back_integration_stepsize, set by default to 7.e-3. If you decrease it e.g. to 6.e-4 you will have >50'000 values in output:

back_integration_stepsize = 6.e-4

All precision parameters are declared and explained/commented inside the structure "precision" in include/common.h. They are grouped by module, starting from the background module. Their default values can be seen in source/input.c and changed by passing them as normal parameters in your input file.

**Comment by mirandawelber** [comment]
Thanks very much for this complete answer and your invaluable support!
