### ISSUE TITLE
How to call CLASSY from a specific folder?

### ISSUE THREAD

**Issue by mirandawelber** [lesgourg/class_public#152]
Dear All, 

I have diferentt folders with modificatons of CLASS. I wish to call the python wraper (CLASSY) within a specific folder/version. Right now it´s stuck to a folder specific (i don´t know to control).

How to do this? 

Very grateful with some help.
Thanks in advance,

[Uploading Captura de Tela 2017-05-20 às 18.49.14.png.pdf…]()

**Comment by lesgourg** [comment]
Hi Miranda, each time that you compile inside a given class directory with "make clean; make" (or "make clean; make all", it's the same) the python wrapper of that directory is recompiled and reinstalled. Later, when you are in a python shell and you type "import classy" or "from classy import ...", it should use the version of classy that was compiled the latest.
That's for calling classy from a python shell. When you use MontePython, it's a bit different: you need to specify the right folder of the class version that you want to use in the configuration file passed with the option "--conf <yourfile.conf>" (see an example in default.conf.template).
If any of these doesn't work, please write again.

**Comment by ThomasTram** [comment]
Hi Miranda and others

Sometimes it can be nice to have two different versions of CLASS without recompiling. You can then use MontePythons strategy of adding the specific build to the system path:
````
classy_path = PATH_TO_CLASS/python/build
sys.path.insert(1, classy_path)
from classy import Class
````

Let me also add that if you at some point have compiled an older version of CLASS, you can have a version of classy stuck in the user site-packages. This version would take precedence and you would have to clean it manually. (It happened to me recently..) 
To see if you have a local classy, try
````
ls ~/.local/lib/python2.7/site-packages/
````

Cheers,
Thomas

**Comment by mirandawelber** [comment]
Dear,J. Lesgouges and Thomas Tram.

 Thank you very much for this complete answer!
