### ISSUE TITLE
Error in thermodynamics_init(L:302) while running on cluster

### ISSUE THREAD

**Issue by pchaubal** [lesgourg/class_public#153]
Hi everyone,
We are trying to run montepython with class on cluster. It works well for short chains on the master nodes but attempting to run it on computational node gives the following error and then stops.

`Error in Class: thermodynamics_init(L:302) :error in thermodynamics_helium_from_bbn(ppr,pba,pth);
=>thermodynamics_helium_from_bbn(L:1126) :could not open fA with name /shared_phpc_home/home/girish20/class/class_viscous/bbn/sBBN.dat and mode "r"`

We are clueless about the reason behind this error. It would be a great help if someone could help us.
Thanks in advance.

**Comment by pchaubal** [comment]
We found a solution. While compiling class the Makefile was taking a the path from the master node which was not valid on the computational node. Mentioning the proper path in the make file solved the issue.

Thanks,
Prakrut

**Comment by pauloud** [comment]
Could you give the exact fix please ? We probably meet the same issue
