### ISSUE TITLE
The CLASS gauge for matter power spectrum diagram

### ISSUE THREAD

**Issue by mahtaparsa** [lesgourg/class_public#154]
Hi everybody,
In the CLASS code, there is a possibility to choose either Newtonian or synchronous gauges. My question is that, for the matter power spectrum diagram is the code use the gauge we have defined for it (in perturbations module) or solve the equations in the chosen gauge and then show the diagrams in either gauge. I have used Newtonian gauge, however there is a problem in low k part of the matter power spectrum diagram, I want to know if the code use an optional gauge for diagrams or the gauge which has chosen by the user.

**Comment by ThomasTram** [comment]
Hi

The matter power spectrum in CLASS is always given in the gauge comoving with all matter which is non-relativistic today i.e. a gauge very close to the total matter gauge. The gauge transformation is performed in ````perturbations.c````:
`````
if (ppt->has_source_delta_m == _TRUE_) {
      ppw->delta_m += 3. *ppw->pvecback[pba->index_bg_a]*ppw->pvecback[pba->index_bg_H] * ppw->theta_m/k2;
````
If you comment this line you will get the power spectrum in the computation gauge. Note that the gauge transformation assumes a standard energy conservation equation for all species, something which will be violated for decaying DM or other modifications. The gauge transformation to total matter gauge would be very easy, so one could argue that this would be a better choice. On the other hand there are arguments in favour of the 'matter-comoving' P(k).

Cheers,
Thomas

**Comment by mahtaparsa** [comment]
Dear Thomas,
Thanks for your reply. As I have understood, in the case of decaying dark matter models (or models in which there is no conservation for all species) we should comment the mentioned line in the perturbation module in order to have correct results. In this way, if I am going to solve perturbative equations in the Newtonian gauge, the resulted matter power spectrum would be in this gauge too.
