### ISSUE TITLE
Compiling python wrapper with Intel C Compiler (icc)

### ISSUE THREAD

**Issue by ajcuesta** [lesgourg/class_public#16]
When trying to compile the python wrapper, python/setup.py invokes the wrong compiler (gcc) even though the compiler which is set up in the Makefile is icc. I have bypassed this issue by running manually the compilation commands shown on the screen by replacing any occurrence of 'gcc' with 'icc'.
For OpenMP pararellization, I also needed to include -lpthread flag in OMPFLAG in the Makefile (together with -openmp). I think that's a requirement for Intel Math Kernel Library users.

**Comment by zboralski** [comment]
## Code Location

All code for this investigation:
```
issues/016_class_scalar_field/
├── README.md
├── background.c.patch      # V ∝ H(z)φ² modification
├── perturbations.c.patch   # φ' → δ_b tracking
├── input.c.patch           # param reading, shooting bypass
├── elimination_*.ini       # test configs
└── sweep_*.ini             # coupling sweep configs
```

Original CLASS modifications in:
- `class_modified/source/background.c:2800-2900`
- `class_modified/source/perturbations.c:9407-9428`
- `class_modified/source/input.c:5000-5100`
