### ISSUE TITLE
power spectrum output at chosen k not possible

### ISSUE THREAD

**Issue by VMBoehm** [lesgourg/class_public#193]
Hi,

I know this issue has been posted before, but the suggested solution has not worked for me. I am using the python wrapper and I want to output the linear matter power spectrum at z=0 for a certain k-range.

The error I get is 
Error in Class: spectra_init(L:1297) :error in spectra_pk(pba,ppt,ppm,pnl,psp);
=>spectra_pk(L:2785) :error in spectra_sigma(pba,ppm,psp,8./pba->h,0.,&(psp->sigma8));
=>spectra_sigma(L:2876) :error in spectra_pk_at_k_and_z(pba,ppm,psp,k,z,&pk,pk_ic);
=>spectra_pk_at_k_and_z(L:688) :error in spectra_pk_at_z(pba, psp, logarithmic, z, spectrum_at_z, spectrum_at_z_ic);
=>spectra_pk_at_z(L:418) :error in array_interpolate_spline(psp->ln_tau, psp->ln_tau_size, psp->ln_pk, psp->ddln_pk, psp->ln_k_size, ln_tau, &last_index, output_tot, psp->ln_k_size, psp->error_message);
=>array_interpolate_spline(L:1701) : x=9.516875e+00 > x_max=9.516875e+00

The code is
'output'='tCl mPk'
'tol_perturb_integration'=1.e-6

'P_k_max_1/Mpc'= 50.
'z_max_pk'     = 1.5
'k_min_tau0'=min(k_array)*13000.

------
'k_step_sub'=0.015
'k_step_super'=0.0001
'k_step_super_reduction'=0.1
'k_per_decade_for_pk'=20
'k_output_values'=50.
------
print (min(k_array),max(k_array)) #(0.0010000000000000002, 49.999999999999993)

closmo = Class()
closmo.set(params)
closmo.compute()

P=[closmo.pk(k,0.) for k in k_array]

Adding the parameters between the dashes solved the problem for one cosmology but not the one I need, which is
'omega_cdm':0.129600,
'omega_b':0.023846,
'h':0.720,
'n_s':0.960,
'A_s':1.971*1e-9,
'Omega_k':0.0,
'k_pivot' : 0.002

Do I need to adapt some other precision parameters? Thanks in advance!

Vanessa

**Comment by fkoehlin** [comment]
Hi Vanessa,

This is most likely a duplicate issue and due to compiler hiccup, see #204 (with workaround).

Cheers,

Fabian

**Comment by VMBoehm** [comment]
Hi Fabian,
thanks! yes, I think its the same issue and I have also found a workaround in the meantime ;)
Cheers,
Vanessa
