### ISSUE TITLE
How to get larger k values for WDM linear matter power spectra?

### ISSUE THREAD

**Issue by aevans97** [lesgourg/class_public#219]
Hello,

Whenever I plot the matter power spectra for warm dark matter models, my k value does not go past 2. I have set the max k value to be 100 and that did not fix it. Right now I have:

N_ncdm = 1
m_ncdm = 750
Omega_ncdm = 0.25
T_ncdm = 0.71611
ksi_ncdm = 0
deg_ncdm unspecified 
Quadrature strategy = 0 

I'm also using Grace to generate my plots (not sure if that would make a difference?). Any insight would be very much appreciated!

**Comment by ThomasTram** [comment]
Hi

How did you set the maximum k-value to be 100? Did you use ````P_k_max_1/Mpc = 100````?

Cheers,
Thomas

**Comment by aevans97** [comment]
Hi Thomas,

Yes, that is what I did. I actually realized later that I had to change the
scale to logarithmic to see the matter power spectrum that I am familiar
with. Now I am just attempting to recreate the WDM matter power spectrum
from your NCDM power point that is on the CLASS website. If you don't mind
answering another question, I was wondering if giving the code an input
file of f(q) and q values (as mentioned in the 4th CLASS paper available on
the website) is necessary to generate an accurate WDM power spectrum, or if
I can opt to do it analytically with the phase space distribution.

Thank you very much for your time,
Addy

**Comment by aevans97** [comment]
I am asking this question because I'm not sure how correct my plots are. Below is the matter power spectra of pure CDM (red line) and W+CDM (black line). My .ini file for the CDM is essentially a copy of the explanatory.ini file and the W+CDM .ini file has 

Omega_cdm = 0.15
N_ncdm = 1
use_ncdm_psd_files = 0
m_ncdm = 1000
T_ncdm = 0.1
Quadrature strategy = 0

[dm.pdf](https://github.com/lesgourg/class_public/files/2087286/dm.pdf)

I haven't worked with dark matter before so I'm not sure what it should look like. 

-Addy

**Comment by ThomasTram** [comment]
Hi Addy

I would suggest to start by matching some plots in the literature. In WDM models, the production mechanism is often not thermal, or it has a significant non-thermal contribution, so the distribution function may not be analytically known. The file option is for that purpose, if you are happy with the Fermi-Dirac distribution you should just use that.

Also, you need to turn off the fluid approximation and you should probably also change the quadrature strategy. You can read this related issue https://github.com/lesgourg/class_public/issues/203 and the appendix of the paper referenced in there.

Cheers,
Thomas

**Comment by aevans97** [comment]
Thomas,

Thank you for your response. When I make the changes suggested in the paper
you mentioned and try to run my .ini file, I get the following error
message:
Error running input_init_from_arguments
=>input_init_from_arguments(L:179) :error in input_init(&fc, ppr, pba, pth,
ppt, ptr, ppm, psp, pnl, ple, pop, errmsg);
=>input_init(L:442) :error in input_read_parameters(pfc, ppr, pba, pth,
ppt, ptr, ppm, psp, pnl, ple, pop, errmsg);
=>input_read_parameters(L:890) :error in background_ncdm_init(ppr,pba);
=>background_ncdm_init(L:1256) :could not allocate pba->q_ncdm_bg[k] with
size -8

This is with the following settings:
N_ncdm = 1
m_ncdm = 1000
Omega_ncdm = 0.25
use_ncdm_psd_files = 0
quadrature strategy = 3
q = 15

However, it seems like changing the settings doesn't affect anything
anyway.

-Addy

**Comment by ThomasTram** [comment]
Hi

It seems that you did not use all the settings from table 4 of https://arxiv.org/pdf/1712.03944.pdf, for instance, ````Number of momentum bins = 15```` is missing. Same for ````maximum q```` and ````ncdm_fluid_approximation````.

**Comment by aevans97** [comment]
Thomas,

My apologies, I did have q max = 15, the fluid approximation set to 3, and
l_max_ncdm = 15. I think it may just be an issue of finding where I can
specify number of momentum bins in the code. I have attempted to change
several parameters thinking that it was the number of momentum bins but I
am still getting the same error message.

-Addy

**Comment by ThomasTram** [comment]
Hi again

The setting is really just
````Number of momentum bins = 15````
as I wrote.

**Comment by aevans97** [comment]
Okay. I did not understand that it could just be written in. Thank you for
your time! I'll close this issue now.
