### ISSUE TITLE
"Spiky" WDM linear matter power spectrum oscillations

### ISSUE THREAD

**Issue by aevans97** [lesgourg/class_public#222]
Hello,

I am attempting to match WDM matter power spectra to the ones shown on page 16 in the following paper: arXiv:1104.2935 [astro-ph.CO]

I find that the simulations match very well, except the oscillations are spikier than the curved oscillations in the paper. I am wondering if this is due to the integration step sizes being too large? I am using the following parameters:

Omega_cdm = 10.e-20
N_ncdm = 1
use_ncdm_psd_files = 0
m_ncdm = 1000
Omega_ncdm = 0.25
T_ncdm = 0.71611
ksi_ncdm = 0
deg_ncdm = 1.0
Quadrature strategy = 3
Maximum q = 15
Number of momentum bins = 15
ncdm_fluid_approximation = 3
l_max_ncdm=15
gauge = sync

I have also attached an image of the linear matter power spectrum.
![1kevcompare](https://user-images.githubusercontent.com/40038356/42116044-38028aec-7bbb-11e8-81ae-ba23aafdb078.png)

Any help would be appreciated!

**Comment by Stefan-Heimersheim** [comment]
Hey,

> I am wondering if this is due to the integration step sizes being too large?

your k-steps are too large for the detail you want to resolve. Python is just connecting the few dots with straight lines resulting in "spikes". Class computes the value P(k) for a list of k's. This list can be controlled with (among others):
- `P_k_max_h/Mpc`: Defines the biggest k value to compute P(k) for
- `k_per_decade_for_pk`: Defines how "dense" the k values are in general
- `k_per_decade_for_bao`: Defines how "dense" the k values are in the BAO region

If you want to see how this works exactly, you can look around line `1437` of `source/perturbations.c`.

So when you set, for example, `k_per_decade_for_pk = 100` in your parameters, you can resolve the shape of the oscillations.

**Comment by aevans97** [comment]
Stefan,

Thank you for your response! I am getting much better results now.
