### ISSUE TITLE
Conversion between synchronous and Newtonian gauge for fluid perturbation

### ISSUE THREAD

**Issue by flo1984** [lesgourg/class_public#276]
Dear Class community, I had a look at the conversion between Newtonian and synchronous gauge in the perturbations module for a fluid component. Specifically, I refer to the calculation of delta_fld in line 4481 in perturbations.c which I compared to Eq. 27 a) in Ma&Bertschinger (arXiv: 9506072). If I am not mistaken, there seems to be a sign-mismatch between the implementation and the equation in the paper. Note that I agree with the transformation for theta_fld in the next line. Thank you for double checking.

**Comment by lesgourg** [comment]
Yes, thank you very much! Corrected in v2.9.2. Best, 
Julien
