### ISSUE TITLE
Call function from other species

### ISSUE THREAD

**Issue by DCarlosHe** [lesgourg/class_public#287]
Hello everyone,
I have a model where in the perturbation equation for DM there is a term depending on theta_DE, is there any way I can write this on CLASS without having an error like Segmentation fault?

Thank in advance!

**Comment by Stefan-Heimersheim** [comment]
Hi,

I'm not sure what you are trying to do exactly but this sounds like you want to use the fluid description for DE and then use `delta_fld = y[ppw->pv->index_pt_delta_fld];` in your DM equations? I discussed this with Rodrigo [in this issue](https://github.com/lesgourg/class_public/issues/285), maybe you can find the code you need there?

Best,
Stefan

**Comment by DCarlosHe** [comment]
Hi Stefan, thanks for your response! 

I think is not exactly the same that the one in that issue. I have a model where the perturbation equations of DE and CDM are coupled in a way such that:
 ` dy[pv->index_pt_theta_cdm]= (usual terms) + y[pv->index_pt_theta_fld]
dy[pv->index_pt_theta_fld]= (usual terms) + y[pv->index_pt_theta_cdm]`
The problem I have is to write that in a way CLASS can understand they are coupled and no segmentation fault happens.

Thanks again!

**Comment by Stefan-Heimersheim** [comment]
Ah, I see. `y[pv->index_pt_theta_cdm]` is only there if you are using `gauge = newtonian`, so you have to add this to your ini file. Here is the definition in the code:

    class_define_index(ppv->index_pt_theta_cdm,pba->has_cdm && (ppt->gauge == newtonian),index_pt,1); /* cdm velocity */

Cheers,
Stefan

**Comment by DCarlosHe** [comment]
Hi,

In fact I have already selected `gauge = newtonian` in the ini file.
The problem is not there but in the equation in ` /** - ---> cdm */`
`dy[pv->index_pt_theta_cdm]= (usual terms) + y[pv->index_pt_theta_fld] `
as CLASS has to use `y[pv->index_pt_theta_fld]` which differential equation appears later in ` /** - ---> fluid (fld) */ `. So the problem is that I do not know how to couple the equations.

Sorry if is something easy. I am not an expert on CLASS, thanks!

**Comment by Stefan-Heimersheim** [comment]
I just put these two example lines in `perturbations.c` (here is diff, the first line is at `/** - ---> cdm */`):

    diff --git a/source/perturbations.c b/source/perturbations.c
    index 71738fa5..0dbf5763 100755
    --- a/source/perturbations.c
    +++ b/source/perturbations.c
    @@ -7263,7 +7263,7 @@ int perturb_derivs(double tau,
           if (ppt->gauge == newtonian) {
             dy[pv->index_pt_delta_cdm] = -(y[pv->index_pt_theta_cdm]+metric_continuity); /* cdm density */
     
    -        dy[pv->index_pt_theta_cdm] = - a_prime_over_a*y[pv->index_pt_theta_cdm] + metric_euler; /* cdm velocity */
    +        dy[pv->index_pt_theta_cdm] = - a_prime_over_a*y[pv->index_pt_theta_cdm] + metric_euler + 1e-20*y[pv->index_pt_theta_fld]; /* cdm velocity */
           }
     
           /** - ----> synchronous gauge: cdm density only (velocity set to zero by definition of the gauge) */
    @@ -7367,7 +7367,7 @@ int perturb_derivs(double tau,
             dy[pv->index_pt_theta_fld] = /* fluid velocity */
               -(1.-3.*cs2)*a_prime_over_a*y[pv->index_pt_theta_fld]
               +cs2*k2/(1.+w_fld)*y[pv->index_pt_delta_fld]
    -          +metric_euler;
    +          +metric_euler+y[pv->index_pt_theta_cdm];
           }
           else {
             dy[pv->index_pt_Gamma_fld] = ppw->Gamma_prime_fld; /* Gamma variable of PPF formalism */

And I am using the following changes to `explanatory.ini` (the most important options are `use_ppf` and `gauge`):

    diff --git a/explanatory.ini b/explanatory.ini
    index 0d9daa74..7972da30 100755
    --- a/explanatory.ini
    +++ b/explanatory.ini
    @@ -165,8 +165,8 @@ Omega_k = 0.
         (default: 'Omega_fld' and 'Omega_scf' set to 0 and 'Omega_Lambda' inferred
         by code)
     
    -# Omega_Lambda = 0.7
    -Omega_fld = 0
    +Omega_Lambda = 0
    +# Omega_fld = 0
     Omega_scf = 0
     
     8b) The flag 'use_ppf' is 'yes' by default, to use the PPF approximation
    @@ -177,7 +177,7 @@ Omega_scf = 0
         default is 0.4 as recommended by that reference, and implicitely
         assumed in other codes. (default: 'use_ppf' to yes, 'c_gamma_over_c_fld' to 0.4)
     
    -use_ppf = yes
    +use_ppf = no
     c_gamma_over_c_fld = 0.4
     
     8c) Choose your equation of state between different models, 'CLP' for
    @@ -195,8 +195,8 @@ fluid_equation_of_state = CLP
         the function background_w_fld().  (default: 'w0_fld' set to -1,
         'wa_fld' to 0, 'cs2_fls' to 1)
     
    -w0_fld = -0.9
    -wa_fld = 0.
    +w0_fld = -0.8
    +wa_fld = -0.1
     cs2_fld = 1
     
     8c2) equation of state of the fluid in 'EDE' case and squared sound speed 'cs2_fld' of the fluid
    @@ -207,9 +207,9 @@ cs2_fld = 1
         the function background_w_fld().  (default: 'w0_fld' set to -1,
         'Omega_EDE' to 0, 'cs2_fls' to 1)
     
    -w0_fld = -0.9
    -Omega_EDE = 0.
    -cs2_fld = 1
    +# w0_fld = -0.9
    +# Omega_EDE = 0.
    +# cs2_fld = 1
     
     8d) Scalar field (scf) initial conditions from attractor solution (assuming
         pure exponential potential). (default: yes)
    @@ -482,7 +482,7 @@ ic = ad
        Newtonian/longitudinal gauge
        (default: set to synchronous)
     
    -gauge = synchronous
    +gauge = newtonian
     
     ---------------------------------------------
     ----> define primordial perturbation spectra:
    @@ -813,7 +813,7 @@ write thermodynamics = no
         wavenumbers k? Dimension of k is 1/Mpc. The actual wave numbers are chosen
         such that they are as close as possible to the requested k-values.
     
    -k_output_values = #0.01, 0.1, 0.0001
    +k_output_values = 0.01, 0.1, 0.0001
     
     7g) Do you want to write the primordial scalar(/tensor) spectrum in a file,
         with columns k [1/Mpc], P_s(k) [dimensionless], ( P_t(k) [dimensionless])?

Other than this, I'm using the unmodified public CLASS 2.7.2 code. Maybe you could post a (simplified) version / diff of your code that is producing the segfault?

**Comment by DCarlosHe** [comment]
Hi,

You are totally right, I change in the way you put here and some of the changes of the ini file make everything work. 

I am very grateful you helped me!!
