### ISSUE TITLE
Typo in perturb_initial_conditions

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [lesgourg/class_public#288]
In `int perturb_initial_conditions` in `perturbations.c` there seems to be a typo in [line 4481](https://github.com/lesgourg/class_public/blob/master/source/perturbations.c#L4481) noticed by Manuel.

Currently it reads:

     ppw->pv->y[ppw->pv->index_pt_delta_fld] += 3*(1.+w_fld)*a_prime_over_a*alpha;

But he thinks it should be with a `-=`:

     ppw->pv->y[ppw->pv->index_pt_delta_fld] -= 3*(1.+w_fld)*a_prime_over_a*alpha;

Best,
Stefan

**Comment by flo1984** [comment]
Hi Stefan, I noticed the same typo. See my recent post #276. So, I agree with Manuel. It's only relevant if you use Newtonian gauge though. Best, Florian

**Comment by lesgourg** [comment]
Thanks to both for seeing this! This is finally corrected in v2.9.2. Best, Julien
