### ISSUE TITLE
Typo when omega_m is a derived parameter?

### ISSUE THREAD

**Issue by ahallcosmo** [lesgourg/class_public#306]
Hi,

In the function get_current_derived_parameters in classy.pyx, should the lines 

elif name == 'omega_m':
value = self.ba.Omega0_m/self.ba.h**2

in fact read

elif name == 'omega_m':
value = self.ba.Omega0_m*self.ba.h**2

in line with the usual convention that omega_m = Omega_m * h**2 ?

Best regards,
Alex

**Comment by lesgourg** [comment]
Thanks Alex, you are of course completely right. This is now corrected in v2.9.2. Best,
Julien
