### ISSUE TITLE
segfault in class v2.9 when computing A_s given sigma8

### ISSUE THREAD

**Issue by emiliobellini** [lesgourg/class_public#310]
Hi all,
I think I found a small bug that can cause segmentation fault in v2.9 of Class. This is a minimal input that allows to reproduce it

output = mPk
sigma8 = 0.8

I tracked down the error and it is raised at line 939 of perturbations.c. The code tries to free ppt->beta_idr but it's not defined. A quick and dirty workaround is to comment that line, but clearly it is not ideal.
To be more specific, this error happens at the end of the function "input_try_unknown_parameters", when the code tries to free the structures after the shooting.
It is interesting to notice that commenting out "sigma8 = 0.8" the code runs well. So, apparently if perturb_free is called after a normal evaluation of perturbations Class is happy. Can this be a compiler dependent thing? (mine is gcc 7.4.0 on Ubuntu 18.04)
Also, I do not understand why ppt->alpha_idm_dr is not giving the same error, but probably in some cases it could..

Cheers,
Emilio

**Comment by lesgourg** [comment]
Many thanks Emilio for noticing this! This has been corrected a few weeks ago in 2.9.1. Best, Julien
