### ISSUE TITLE
BBN pipeline

### ISSUE THREAD

**Issue by flo1984** [lesgourg/class_public#311]
Hi, 

I wanted to double check that the BBN interpolation table sBBN_2017.dat is based on the nuclear rate d(p,\gamma)3He from Adelberger et al. in arXiv:1004.2318 ?

Thank you for letting me know.

Best, Florian

**Comment by lesgourg** [comment]
Hi Florian,
Correct: bbn/sBBN_2017.dat is based on Adelberger et al. arXiv:1004.2318 , while bbn/sBBN_2017_marcucci.dat is based on the ab initio calculation. Both are computed using the most recent Parthenope. (See Planck cosmological parameter paper 2018 for more details: the discussion and the results of the BBN section match precisely these two files).
Julien
