### ISSUE TITLE
possible bug in perturb_total_stress_energy

### ISSUE THREAD

**Issue by emiliobellini** [lesgourg/class_public#313]
Hi all,
in older version there was a local variable defined perturb_total_stress_energy called "rho_plus_p_tot". Now this variable has been defined in the perturb workspace ppw.
The problem is that in the latest version of Class we have a mixed use of "rho_plus_p_tot" and "ppw->rho_plus_p_tot", and I think that everything should be "ppw->rho_plus_p_tot".

Cheers,
Emilio

**Comment by lesgourg** [comment]
Many thanks Emilio for noticing this! This is now corrected in 2.9.2. Your help is very much appreciated. Best, Julien
