### ISSUE TITLE
Properties of the transformation cosmo params -> power spectrum

### ISSUE THREAD

**Issue by Gabriel-Ducrocq** [lesgourg/class_public#314]
Hi,

I am not sure this is the right place to ask such a question but I have no idea where to ask for this. So excuse me if this is not the appropriate place.

For a fixed L_max, is the transformation cosmological parameters --> power spectrum a bijection ? A surjection ? An injection ? Neither of these three options ?

My cosmological background is limited and I couldn't find an answer on my own.

Thank you,
Gabriel.

**Comment by Stefan-Heimersheim** [comment]
Hi,

I'm not completely sure with these terms anymore but it certainly isn't a bijection:

* There exists points in the codomain (power spectrum) that cannot be reached with any cosmological parameters (assuming LCDM), just thing of a completely ridiculous power spectrum. I think this means it's *not surjective*
* Every parameter point maps on exactly one point in the codomain (just the result of the computation). I think this means it's *injective*

But yeah, I think you might be better of in a general cosmology forum like https://cosmocoffee.info/

**Comment by Gabriel-Ducrocq** [comment]
Hi Stefan, 

Thanks for answering ! 

Okay it is not a surjection for sure then. As for the injection part, the question is more: is it possible that two different parameters set lead to the same power spectrum ?

What do you think ?

Thanks for the link,
Gabriel.

**Comment by Stefan-Heimersheim** [comment]
Ah, OK. Some effects depend only on e.g. the angular scale of sound horizon which is the same for various combinations of parameters.

However taking into account all effects I suspect that every (standard) parameter combination would give you a different power spectrum and you could distinguish them if you could measure it perfectly.

**Comment by Gabriel-Ducrocq** [comment]
Hmmm okay, thank you, I ll go through the forum and see.

Thank you,
Gabriel.
