### ISSUE TITLE
Small bug in nonlinear.c

### ISSUE THREAD

**Issue by emiliobellini** [lesgourg/class_public#315]
Hi,
in nonlinear.c the function"nonlinear_pks_at_kvec_and_zvec" has a small bug.
Line 810 now reads "if (pnl->has_pk_m) {".
It should be replaced by "if (pnl->has_pk_cb) {".

Cheers,
Emilio

**Comment by lesgourg** [comment]
Many thanks Emilio for noticing this! This is now corrected in 2.9.2. Best, Julien
