### ISSUE TITLE
Differences between CLASS and CAMB when varying w?

### ISSUE THREAD

**Issue by aoifeboyle** [lesgourg/class_public#340]
Hello. I'm calculating the numerical derivative of the matter power spectrum with respect to the dark energy equation of state parameter w_0. I find that I get different results using CLASS and CAMB, and was wondering if there is any difference in the definition or treatment of w between the two codes that might explain this. 

This figure shows the difference: [Derivative plot](https://github.com/lesgourg/class_public/files/4736102/test.pdf)

I have thoroughly checked that the cosmological parameters match between the two cases. This is the code that I use to generate the CLASS data:

```
import numpy as np
from astropy import constants
from classy import Class
import pylab
from scipy.interpolate import interp1d as interp

def class_test():
    #Set k values
    log_kmin = np.log10(1.e-4)
    log_kmax = np.log10(1.)
    npoints = (log_kmax - log_kmin) * 50.
    ks = np.logspace(log_kmin, log_kmax, npoints)
    np.savetxt('class_camb/class_test_ks.dat', ks)

    #Set cosmology, set w_0 = -0.96
    cosmo = Class()
    cosmo.set({'omega_cdm':0.11977, 'sigma8':0.842, 'w0_fld':-0.96, 'Omega_Lambda': 0.0, 'H0': 67.31, 'n_s':0.9658,
               'omega_b':0.022242, 'tau_reio':0.0781, 'k_per_decade_for_pk':200, 'k_per_decade_for_bao':200,
               'output':'mPk'})

    #Calculate for w_0 = -0.96 and save
    cosmo.compute()
    h = cosmo.get_background()['H [1/Mpc]'][-1] * constants.c.value / 1.e5
    ks_mpc = ks*h # Correcting units to h/Mpc, Mpc^3/h^3
    pk_inc = np.zeros_like(ks)
    for kindex in range(len(ks)):
        pk_inc[kindex] = cosmo.pk(ks_mpc[kindex], 0.0)*h**3.
    np.savetxt('class_camb/class_test_w+.dat', pk_inc)

    #Calculate for w_0 = 1.04 and save
    cosmo.set({'w0_fld':-1.04})
    cosmo.compute()
    pk_dec = np.zeros_like(ks)
    for kindex in range(len(ks)):
        pk_dec[kindex] = cosmo.pk(ks_mpc[kindex], 0.0)*h**3.
    np.savetxt('class_camb/class_test_w-.dat', pk_dec)
    return

```
I don't want to post my CAMB input files here because they were provided to me by someone but I can send them directly if needed. I have tried several things to resolve this, including setting A_s to match CAMB instead of sigma8, but the results remain the same. I should also note that derivatives with respect to other cosmological parameters I have checked match identically. I would really appreciate any advice on this! 

Thank you,

Aoife

**Comment by ThomasTram** [comment]
Hi

Just a quick thing that you could check : CLASS use a dark energy fluid by default while CAMB (as I remember) use the PPF approximation. You can force CLASS to use PPF - I think the flag is something like use_ppf.

Cheers,
Things

**Comment by aoifeboyle** [comment]
Hi @ThomasTram, thanks very much! The inverse actually worked - when I set CLASS to 'use_ppf':'no' the difference was reconciled. Thanks very much for your help!
