### ISSUE TITLE
A derivative in w(a)

### ISSUE THREAD

**Issue by progsymrock** [lesgourg/class_public#346]
Hi everybody, I have a question:

Is it possible to write a w(a) equation in background.c with a' (first derivative of the scale factor with respect to the conformal time) terms? How it could be written in the code?

Thanks!

**Comment by ShazAlvi** [comment]
If I remember correctly, you can provide the evolution of the equation of state of dark energy fluid in a file. You will have to look background.c for the portion of the code that reads the provided file. I cannot remember where this code is but I remember looking at this option while exploring something else. Good luck!!
