### ISSUE TITLE
How to initialize SCF model in Montepython?

### ISSUE THREAD

**Issue by nkhadk** [lesgourg/class_public#355]
I am new at Montepython. I want to use Montepython to extract cosmological parameters using the SCF model. I tried to write a .param file for the SCF model but it gave me an error message which is given below.

Something went wrong when calling CLASS
/_o_\  Error in Class: input_init(L:455) :error in
       input_read_parameters(&(fzw.fc), ppr, pba, pth, ppt, ptr, ppm, psp, pnl,
       ple, pop, errmsg);
       =>input_read_parameters(L:1396) :condition (pba->scf_tuning_index >=
       pba->scf_parameters_size) is true; Tuning index scf_tuning_index = 0 is
       larger than the number of entries 0 in scf_parameters. Check your .ini
       file.

Could anyone suggest to me how to run the SCF model in Montepython? Any suggestions will be appreciated.

Thank you

Narayan

**Comment by gaby7646** [comment]
Do you remember how did you solve this issue?
