### ISSUE TITLE
Mismatch between CLASSY and CLASS Nonlinear Matter Power Spectrum

### ISSUE THREAD

**Issue by ShazAlvi** [lesgourg/class_public#367]
While working with MontePython, I compared the non-linear matter power spectrum from CLASSY (through MontePython) and that produced by CLASS output. In both the platform I use Halofit set to nonlinear matter power spectrum. However, when I take the ratio of the matter power spectrum of CLASS/CLASSY and MontePython/CLASS, there seems to be a mismatch. I am attaching the plot of the ratio along with the parameter files used in making this plot. Note: In the plots, the two curves overlap. 

Has anyone encountered this mismatch before? Also, if so, then is there a way around this? 

![Comp_Ratio_CLASSY_MontePython_CLASS](https://user-images.githubusercontent.com/63428526/97306454-ccfc2080-185e-11eb-8a01-ffcc8f7f14b8.png)
[Param_validation.txt](https://github.com/lesgourg/class_public/files/5445600/Param_validation.txt)
[Validation_Param.txt](https://github.com/lesgourg/class_public/files/5445486/Validation_Param.txt)

**Comment by ThomasTram** [comment]
Hi

Just a quick thought: Did you remember to take into account that the wave number in the output files from CLASS uses h/Mpc and not 1/Mpc? And similarly for P(k) which is Mpc/h)^3 in the output file and Mpc^3 from classy?

Cheers,
Thomas

**Comment by ShazAlvi** [comment]
Thank you for the quite reply @ThomasTram . You are right in pointing out the difference in the unit conversion. Once account for, the ratio is plotted below: 

![image](https://user-images.githubusercontent.com/63428526/97324126-caef8d00-1871-11eb-8e5d-a6ed2f506f82.png)

**Comment by ShazAlvi** [comment]
I am going to leave just one more quick update here. The wiggles in the above plot are due to the artifacts of the interpolation which was done in order to take the ratio at the right values of wavenumber. When the power spectrum is asked from CLASS at the correct wavenumber (thus not needing any interpolation) the ratio is nicely equal to 1 for "most" part of the wavenumber space. 

![image](https://user-images.githubusercontent.com/63428526/97336522-6804f280-187f-11eb-8743-06604deb00cb.png)
