### ISSUE TITLE
TT, TE and EE from CLASS and MontePython

### ISSUE THREAD

**Issue by ShazAlvi** [lesgourg/class_public#381]
I am using MontePython for my work with temperature and galaxy cross-correlations. I am calling the temperature and polarization (TT, TE and EE) power spectra from CLASS in MontePython (through CLASSY, I suppose). When I compare the power spectra between MontePython and those that CLASS produces as output for the same parameters, I get a mismatch. Here is the comparison of the power spectra and their ratio. 
![image](https://user-images.githubusercontent.com/63428526/104001995-bb10f500-51a0-11eb-91f5-572b7d11157f.png)
![image](https://user-images.githubusercontent.com/63428526/104002154-f3183800-51a0-11eb-9d31-470e2b6c108c.png)
![image](https://user-images.githubusercontent.com/63428526/104002361-42f6ff00-51a1-11eb-9332-4c941d4aec33.png)
![image](https://user-images.githubusercontent.com/63428526/104002500-76398e00-51a1-11eb-83a0-d748289aba01.png)
![image](https://user-images.githubusercontent.com/63428526/104002592-95382000-51a1-11eb-8dc9-3ddced7772d9.png)
![image](https://user-images.githubusercontent.com/63428526/104002716-bc8eed00-51a1-11eb-9d1a-9d0a1cb82721.png)
The parameter files for MontePython and CLASS are attached in this message.
[MontePython.txt](https://github.com/lesgourg/class_public/files/5786599/MontePython.txt)
[CLASS.txt](https://github.com/lesgourg/class_public/files/5786639/CLASS.txt)

My question is: Is this a known situation and that it is normal to have this much deviation between CLASS output and MontePython power spectra? If yes, this much deviation appears to be significant for what I am doing. Is there a way around this? 

Thanks for your time and effort.

**Comment by ThomasTram** [comment]
Hi

How do you get the MontePython spectra? MontePython just calls CLASS through `classy`, so there should be no difference at all. Things to check:
- Did you run MontePython with `-f 0 -N 1` to make sure that the parameters are exactly the same as in your input file? (I.e. avoid the initial small jump?)
- Are you comparing with the lensed Cls from CLASS?
- Are you using the same version of CLASS, i.e. is the version of CLASS pointed towards in `default.conf` (or the configuration file that you are using) inside MontePython the same as the one you are using for computing the spectra from CLASS?

My guess is that you are in fact comparing slightly different cosmologies.

Cheers,
Thomas

**Comment by ShazAlvi** [comment]
Hi @ThomasTram ,

Thanks for your prompt reply. I get the power spectra using the command get_cl. 

- Yes, I ran MontePython with `-N 1 -f 0`
- No, I am not comparing with lensed Cl. 
- I only have one version of CLASS so there is no version mismatch.
Just now I also tried to compare another quantity that I use in my calculation the conformal distance and compared the ratio MontePython\CLASSY and MontePython\CLASS. In the plot, the conformal distance for CLASS is taken from the CLASS background file. Here is the plot,
![image](https://user-images.githubusercontent.com/63428526/104018666-7b570700-51ba-11eb-87ca-161ecd4734f5.png)

**Comment by ShazAlvi** [comment]
Also, I have checked that lensing is included in both MontePython and CLASS.

**Comment by ShazAlvi** [comment]
Hi @ThomasTram, 
As you suggested there, was a minor difference in the omega_b (0.02253 instead of 00.22253). But there is still a difference in the Power Spectra. The resultant difference between the plots that I showed before is this, 

![image](https://user-images.githubusercontent.com/63428526/104188473-907da100-5419-11eb-8f6d-80f3232d37e9.png)
![image](https://user-images.githubusercontent.com/63428526/104188437-85c30c00-5419-11eb-955b-578532aa7002.png)

So, the  $/chi(z)$ is the same between CLASS and MontePython (which I think suggests that the cosmologies are indeed the same) but the difference between the power spectra is still significant. Just to clarify one thing about lensing: While the lensing parameter is set to yes for both CLASS and MP, I am making the comparison with the CLASS Cl file called *"_cl_lensed.dat".

Other than this, I have checked the parameter file MP passes to CLASS (by writing data.cosmo_arguments['write parameters'] = 'yes') in the code. This resultant ini file produced file also confirms that the parameters are the same between MP and CLASS.

**Comment by ShazAlvi** [comment]
Just want to give an update on this matter and close the issue. After taking the ini file from MontePython and feeding it to CLASS, I get the following comparison which effectively solves the tension in TT. The updated TT plot looks like this, 
![image](https://user-images.githubusercontent.com/63428526/110207962-9bd3d280-7e86-11eb-9b51-57df653437f0.png)
![image](https://user-images.githubusercontent.com/63428526/110207966-a2fae080-7e86-11eb-8d64-c5b5fa16b614.png)
And there is no tension between the two as far as TT spectrum is considered. There is still tension in TD between CLASS and CLASSY for which I have opened another issue #401.
