### ISSUE TITLE
Temperature-Galaxy and Galaxy-Galaxy power spectrum 

### ISSUE THREAD

**Issue by ShazAlvi** [lesgourg/class_public#385]
I am trying to use CLASSY to get density_cl(). My question is: How do I pass the mean of the bins for multiple bins and also pass the option, non_diagonal?

If I pass multiple bin means as an array of numbers in the dictionary key 'selection_mean', I get the following error,

```
Error in Class: input_init(L:467) :error in input_read_parameters(&(fzw.fc), ppr, pba, pth, ppt, ptr, ppm, psp, pnl, ple, pop, errmsg);
=>input_read_parameters(L:2562) :error in parser_read_list_of_doubles(pfc, "selection_mean", &(int1), &(pointer1), &flag1, errmsg);
=>parser_read_list_of_doubles(L:445) :condition (sscanf(string_with_one_value,"%lg",&(list[i-1])) != 1) is true; could not read 1th value of list of parameters 'selection_mean' in file 'NOFILE'
```
For the other question, I have seen the key 'non_diagonal' being passed, just like another dictionary item, in another matter in the issues but in my case, I get the error that the key 'non_diagonal' is not recognized,

`Error in Class: Class did not read input parameter(s): non_diagonal`

**Comment by janinarenk** [comment]
Hey, 
Would you post an input dictionary that produces this error? Then it's easier to figure out what's going on.

**Comment by ShazAlvi** [comment]
Of course, I should have done this already. 

{'output': 'tCl dCl pCl lCl mPk', 'P_k_max_1/Mpc': 15.705,
            'z_max_pk': 2.5, 'non linear':  'halofit', 'l_max_scalars': 2500,
            'lensing': 'yes', 'l_max_lss': 500, 'omega_b': 0.022253,
            'omega_cdm': 0.11919, 'ln10^{10}A_s': 3.0753, 'n_s': 0.96229,
            '100*theta_s': 1.0418, 'tau_reio': 0.0590,
            'selection': 'gaussian', 'selection_mean': [0.901, 1.329],
            'selection_width': 0.5, 'dNdz_selection': 'analytic',
            'gauge': 'Newtonian', 'non_diagonal': 2}

**Comment by janinarenk** [comment]
The problem is the format how you were passing the values of the selection means. The expected input format is a string of floats separated by commas, so in your case `selection_mean': '0.901,1.329'` . As you have only 2 bins, the maximum number of non-diagonal terms is 1. 

The input that should work is then

```
indict = {'output': 'tCl dCl pCl lCl mPk', 'P_k_max_1/Mpc': 15.705,
'z_max_pk': 2.5, 'non linear': 'halofit', 'l_max_scalars': 2500,
'lensing': 'yes', 'l_max_lss': 500, 'omega_b': 0.022253,
'omega_cdm': 0.11919, 'ln10^{10}A_s': 3.0753, 'n_s': 0.96229,
'100*theta_s': 1.0418, 'tau_reio': 0.0590,
'selection': 'gaussian', 'selection_mean': '0.901,1.329',
'selection_width': 0.5, 'dNdz_selection': 'analytic',
'gauge': 'Newtonian', 'non_diagonal': 1}
```

**Comment by ShazAlvi** [comment]
Hi @janinarenk Thanks for your message and for your patience. The parameters seem to be doing through fine and there is no problem in computing the Cl. Actually, I have three redshift bins and the parameters for the 3 redshift bins are as follows, 

params_1 = {'output': 'tCl dCl pCl lCl mPk', 'P_k_max_1/Mpc': 15.705,
            'z_max_pk': 2.5, 'non linear':  'halofit', 'l_max_scalars': 2500,
            'lensing': 'yes', 'l_max_lss': 500, 'omega_b': 0.022253,
            'omega_cdm': 0.11919, 'ln10^{10}A_s': 3.0753, 'n_s': 0.96229,
            '100*theta_s': 1.0418, 'tau_reio': 0.0590,
            'selection': 'gaussian', 'selection_mean': '0.49, 0.901, 1.329',
            'selection_width': 0.5, 'dNdz_selection': 'analytic',
            'non_diagonal': '2'}

I can see that there are 5 galaxy-galaxy correlations correct for the value of the non_diagonal parameter. However, there is only one column for temperature-galaxy correlation, but there should be three (one for each galaxy bin). Am I missing any additional parameter to call the rest of the td correlations? 

Thanks once again for your time.

**Comment by ThomasTram** [comment]
Hi @ShazAlvi , can we close this now given the answer in https://github.com/lesgourg/class_public/issues/427?

**Comment by ShazAlvi** [comment]
Yup. Thanks a bunch!
