### ISSUE TITLE
using CLASS on Windows

### ISSUE THREAD

**Issue by lemiche** [lesgourg/class_public#39]
Dear CLASS developer,

As uncommon as it is in the community, I am (not proudly) a Windows OS user.

I am trying to build your CLASS library with no success, since the makefile should be modified to fit Windows, and currently I don't know how to.

I have the Code::Blocks installed which includes a MINGW with a gcc compiler.
So I get errors when I "mingw32-make" in my cmd.

Please help, I don't know anyone else who works with Windows, and I have no option to switch.

Many thanks

**Comment by ThomasTram** [comment]
Hi there

First of all, in most cases installing Virtualbox (or another virtualisation tool) with Linux inside is the easiest and most painless way of using CLASS from Windows. But if you really want to compile on Windows it should be possible after some minor modifications.

The first problem is the Makefile, which contains some bash specific commands. I don't have a windows machine at hand, so I will just mention the problems I know is there and you will have to tell me about the remaining problems..

1) search the makefile for *rm* and replace by *del*, the windows equivalent of deleting a file.
2) Does line number 4 work? It might, but if not, just write ````MDIR = C:/Codes/Class```` or whatever your full path to CLASS is. I am pretty sure that windows understands slash as equivalent to backslash in paths by the way, so no need to change anything there.
3) Substitute line 8 and 9 by the following three lines
````
rd /s /q build
mkdir $(WRKDIR) ; mkdir $(WRKDIR)/lib
cd build; type nul >>.base & copy .base +,,
````
Note that I did not test this myself, so let me know if it does not work.

Good luck,
Thomas

**Comment by lemiche** [comment]
Thank you for your prompt response :-)

I actually do want to keep working/compiling on Windows.
Indeed, it seems that the problems come from the top of the Makefile which now looks like:

MDIR := C:/Users/Michele/Desktop/myclass
WRKDIR = $(MDIR)/build

.base:
	rd /s /q build
	mkdir $(WRKDIR) ; mkdir $(WRKDIR)/lib
	cd build; type nul >>.base & copy .base +,,

When I try to clean or build I get the following:
C:\Users\Michele\Desktop\myclass>mingw32-make clean            
 rd /s /q build                                                  
The system cannot find the file specified.                      
Makefile:8: recipe for target '.base' failed                    
mingw32-make: *** [.base] Error 2          

Any ideas? It must be simple, but I just don't know how to fix it.                     

BTW, what do you mean by "The first problem is the Makefile"? Are there other problems expected with CLASS on WIndows? Am I the first Windows user ever to explore CLASS? :-)

Cheers

**Comment by ThomasTram** [comment]
Hi,
did you remember to Tab-indent the 3 lines under .base? I think you should manually create a folder named build inside the class directory so the rd command does not fail. 

I remember having compiled an early version of CLASS on Windows myself, but you are definitely amongst the first.. Let's see if there are other problems..

**Comment by lemiche** [comment]
Hi there,
Yes, the 3 line are tabbed.
When I create a folder manually, and then I make clean it dissappears, 
and I get the same log as before:
rd /s /q build
The system cannot find the file specified.
mingw32-make.exe: *** [.base] Error 2
Makefile:8: recipe for target '.base' failed

When I build without clean after creating this "build" folder, I get the log:
Running command: mingw32-make.exe -f Makefile 

rd /s /q build
The system cannot find the file specified.
mingw32-make.exe: *** [.base] Error 2
Makefile:8: recipe for target '.base' failed

Please help, thanks

**Comment by lemiche** [comment]
sorry, in the second case I get the log:
The syntax of the command is incorrect.
mingw32-make.exe: *** [.base] Error 1
rd /s /q build
mkdir C:/Users/Michele/Desktop/myclass/build ; mkdir C:/Users/Michele/Desktop/myclass/build/lib
Makefile:8: recipe for target '.base' failed

I pasted the wrong excerpt above

**Comment by ThomasTram** [comment]
Hi, try add ````2>nul```` at the end of the rd command, like this:
````rd /s /s $(WRKDIR) 2>nul"````
This should keep make from quitting if the build folder do not exist.
Also I just found out that the semicolon for putting multiple commands on one line does not work in windows. You have to change the semicolons to ampersands in some places:
````
mkdir $(WRKDIR) & mkdir $(WRKDIR)/lib
cd build & type nul >>.base & copy .base +,,
cd $(WRKDIR);$(CC) $(OPTFLAG) $(OMPFLAG) $(CCFLAG) $(INCLUDES) -c ../$< -o $*.o
````
There is also a trailing semicolon in the 'clean' target that you need to delete..

**Comment by lemiche** [comment]
Hi, it does not work :-(
Currently the top of my makefile (lines 4-15) is:

MDIR := C:/Users/Michele/Desktop/myclass
WRKDIR = $(MDIR)/build

.base:
	rd /s /s $(WRKDIR)
	mkdir $(WRKDIR) & mkdir $(WRKDIR)/lib
	cd build & type nul >>.base & copy .base +,,
	cd $(WRKDIR) & $(CC) $(OPTFLAG) $(OMPFLAG) $(CCFLAG) $(INCLUDES) -c ../$< -o $*.o

vpath %.c source:tools:main:test
vpath %.o build
vpath .base build

The build log I get is:

Invalid switch - "Users".
mingw32-make.exe: *** [.base] Error 1
rd /s /q C:/Users/Michele/Desktop/myclass/build
Makefile:8: recipe for target '.base' failed

Please, it does not work for some days now..
Maybe you can also try to compile it on a Windows machine to see that it can work?

Many thank!

**Comment by ThomasTram** [comment]
Hi,

okay I installed Windows 7 on a virtual machine, and after some work I got everything to work: This includes OpenMP and the Python wrapper working inside IPython Notebook! If you are not interested in a complete install, use whatever you like.

1. Install Anaconda (I installed Anaconda for 64-bit Windows)
http://continuum.io/downloads
Anaconda comes with a version of MinGW, but it has no OpenMP and no Make.
2. Install TDM-GCC
http://tdm-gcc.tdragon.net/
Make sure to tick the box "openmp". This has to be done manually. Also, make sure to select the 64 bit version assuming that you have chosen Anaconda for 64 bit Windows.
3. Open an "Anaconda Command Prompt"
4. Type ````PATH```` to check the current PATH. It will contain both Anaconda stuff and the TDM-GCC bin folder. However, the TDM-GCC folder needs to be searched *before* the Anaconda stuff, but on my system, the TDM-GCC bin folder came *after* the Anaconda stuff. To fix this (for this session only) type ````PATH=C:\TDM-GCC-64\bin;%PATH%````
5. Download and extract CLASS to a path without spaces, for instance ````c:\Codes\class_public\master````.
6. Change the Makefile according to this (I am showing only the lines which have been changed):
````
MDIR = c:/Codes/class_public-master
...
.base:
	IF EXIST "$(WRKDIR)" (rd /s /q "$(WRKDIR)")
	mkdir "$(WRKDIR)" & mkdir "$(WRKDIR)/lib"
	cd "$(WRKDIR)" & type nul >>.base & copy .base +,,
...
CCFLAG = -g 
LDFLAG = -g 
...
CCFLAG += -D__CLASSDIR__="\"$(MDIR)\""
...
# Try to automatically avoid an error 'error: can't combine user with ...'
# which sometimes happens with brewed Python on OSX:
PYTHONFLAGS=--user

...
%.o:  %.c .base
	cd $(WRKDIR) & $(CC) $(OPTFLAG) $(OMPFLAG) $(CCFLAG) $(INCLUDES) -c ../$< -o $*.o
...
clean:
	IF EXIST "$(WRKDIR)" (rd /s /q "$(WRKDIR)")
	IF EXIST "libclass.a" (del /q libclass.a)
	IF EXIST "$(MDIR)/python/classy.c" (cd "$(MDIR)/python" & del classy.c)
	IF EXIST "$(MDIR)/python/build" (rd /s /q "$(MDIR)/python/build")
````
Note that all the lines determining ````PYTHONFLAGS```` should just be removed do that only ````PYTHONFLAGS=--user```` remains.
7. Comment line 7 in include/background.h:
````
//enum spatial_curvature {flat,open,closed};
````
It is no longer used.
Comment line 8 and 9 in include/transfer.h:
````
//#include <sys/shm.h>
//#include <sys/stat.h>
````
(They are also no longer in use)
8. Type ````mingw32-make```` and CLASS should compile and install the CLASS library!

Cheers,
Thomas

**Comment by lemiche** [comment]
Hurray!!! 
It works! :-)

Thank you very much for your detailed solution, it was really helpful.

Indeed, since I'm not using python, I did not complete install as in your suggestion above.
Then, I just made few further necessary modifications in the Makefile regarding python.

Again, many thanks!!

**Comment by Order1inhomogeneity** [comment]
Hi
I followed these steps but I got this message.
IF EXIST "C:\Codes\class_public-3.2.0/build" (rd /s /q)
/usr/bin/sh: -c: line 1: syntax error near unexpected token `('
/usr/bin/sh: -c: line 1: `IF EXIST "C:\Codes\class_public-3.2.0/build" (rd /s /q)'

Can you please help me with this?
Thanks
