### ISSUE TITLE
Python interface broken with Intel icc

### ISSUE THREAD

**Issue by tririver** [lesgourg/class_public#40]
When I compiled class with intel icc (version 14.0.0, with -O3 flag) and use it with python, I get the below error. Using gcc does not have this problem.

    Python 2.6.9 (unknown, Jul 28 2014, 08:24:16) 
    [GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import classy
        Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
        ImportError: /home/cosmos/users/dc-wang2/.local/lib/python2.6/site-packages/classy.so: undefined symbol: __intel_sse2_strcpy
    >>>

**Comment by baudren** [comment]
Hello,

this is to be expected - you are running a (rather old) Python version which was compiled against GCC 4.3.4. You can not use a cython file compiled with another compiler! 

Two solutions: 
- use gcc for class (which is good enough, I think)
- compile python from source against your icc (and please use at least `python 2.7`).

**Comment by ThomasTram** [comment]
Hi there,
I agree with Benjamins two bullets above, but it *is* possible to compile the wrapper using icc and use in a Python compiled using gcc. It becomes a little tricky, but I have succeeded using Python 2.7.8 compiled using gcc 4.4.7 and icc version 12.0.0. 

The trick is that the Python module in the final step will be linked together using gcc (if gcc was used for compiling Python), but the icc-compiled object files and CLASS library actually support this! Have a look at
https://software.intel.com/sites/products/collateral/hpc/compilers/intel_linux_compiler_compatibility_with_gnu_compilers.pdf
But for this to work, one has to modify the python/setup.py script slightly. What you need to do will depend on the version and installation path of the Intel compiler suite. But let me list my modifications here for reference:
````
libraries=["class","irc","svml","imf"]
library_dirs=["../","/opt/apps/compilers/intel/lib/intel64",GCCPATH],
extra_link_args=["-liomp5","-lgomp"]
````
The extra 3 libraries are the ones listed in Figure 7 of the white paper. The extra library directory is the one containing the intel libraries, and "-liomp5" in the end links to the intel implementation of OpenMP. (It did not work without this). Maybe one can delete the GNU OpenMP "-lgomp", but i did not try.
