### ISSUE TITLE
Class gets stuck (and doesn't produce any outputs after "Computing sources")

### ISSUE THREAD

**Issue by fkoehlin** [lesgourg/class_public#41]
I have just cloned the most recent "class_public" with "git clone https://github.com/lesgourg/class_public.git class" and compiled it with either "make" or "make -j" (for montepython). Running "./class explanatory.ini" then as a sanity check seems to get stuck in/after the step "Computing sources" (i.e. no further output for >hours; check with"top/htop" shows that class is still running on all available cores...). However, pulling the branch "2.4" and compiling it the same way yields a proper class run with output-files within a second.

**Comment by lesgourg** [comment]
Thanks for the healthy warning, I will check what is going on!
Best
Julien
________________________________

**Comment by fkoehlin** [comment]
Apologies for the late reply, but I forgot about checking for updates.
Deeply embarrassed I have to admit though that I was too fast in opening this thread: I might just have forgotten to execute Class in a *new* terminal window instead of calling it from the same terminal in which I had compiled it...
