### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by am610** [lesgourg/class_public#410]
Running on a Mac OS 10+ 
This is the error I get.
I have installed cython via

`pip install cython`
still this error
 
```
ImportError: No module named Cython.Distutils
Traceback (most recent call last):
  File "autosetup.py", line 3, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
make: *** [classy] Error 1

```

**Comment by ThomasTram** [comment]
Hi

Do you use Anaconda Python? Otherwise, switch to that one instead of using the system Python. If the problem persists, you have to check which Python and pip you are using. Try this:
```bash
which python
which pip
```
For instance, your pip may refer to Python2 pip and there could be a pip3 you need to use.

Cheers,
Thomas

**Comment by am610** [comment]
Works.
