### ISSUE TITLE
Shooting failed for Dark Matter decay quantities

### ISSUE THREAD

**Issue by astrogirl1** [lesgourg/class_public#412]
Hi, 

I am trying to run CLASS alone and have provided values for '_Omega_dcdmdr = 0.23'_ OR '_Omega_ini_dcdm'_ . As I understand it, if one is given the other is automatically found through shooting. My intention is to get a non-zero _'Omega0_dcdmdr'_ which in turn will make '_has_dcdm_' TRUE. 

But no matter what value I supply in explanatory.ini, for ( '_Omega_dcdmdr'_ OR '_Omega_ini_dcdm'_ ) I **get this shooting error** :

```
Reading input parameters
Computing unknown input parameter 'Omega_ini_dcdm' using input parameter 'Omega_dcdmdr'
 -> matched budget equations by adjusting Omega_Lambda = 4.578622e-01
 -> matched budget equations by adjusting Omega_Lambda = 4.578622e-01
 -> found 'Omega_ini_dcdm = 0.000000e+00'
 -> matched budget equations by adjusting Omega_Lambda = 4.578622e-01
Running CLASS version v2.9.4
Computing background

Error running background_init 
=>background_init(L:703) :condition (pba->shooting_failed == _TRUE_) is true; Shooting failed, try optimising input_get_guess(). Error message:

input_init(L:393) :error in input_find_root(&xzero, &fevals, &fzw, ppr->tol_shooting_1d, errmsg);
=>input_find_root(L:4076) :error in input_fzerofun_1d(x1, pfzw, &f1, errmsg);
=>input_fzerofun_1d(L:3550) :error in input_try_unknown_parameters(&input, 1, pfzw, output, error_message);
=>input_try_unknown_parameters(L:3747) :error in background_init(&pr,&ba);
=>background_init(L:746) :error in background_solve(ppr,pba);
=>background_solve(L:1746) :error in generic_integrator(background_derivs, tau_start, tau_end, pvecback_integration, &bpaw, ppr->tol_background_integration, ppr->smallest_allowed_variation, &gi);
=>generic_integrator(L:112) :error in rkqs(&x, h, eps, &hdid, &hnext, derivs, parameters_and_workspace_for_derivs, pgi);
=>rkqs(L:146) :error in rkck(*x,h,derivs,parameters_and_workspace_for_derivs,pgi);
=>rkck(L:184) :error in (*derivs)(x+0.2*h, pgi->ytemp, pgi->ak2, parameters_and_workspace_for_derivs, pgi->error_message);
=>background_derivs(L:2400) :error in background_functions(pba, y, pba->normal_info, pvecback);
=>background_functions(L:482) :condition (rho_crit <= 0.) is true; rho_crit = -4.442375e+45 instead of strictly positive

```

I am currently on CLASS 2.9.4. I accidentally git pulled and got the new changes for the new version about a week ago, but this was not an issue before then. I tried going back to the old version but now I consistently get this shooting error. (Through Class and also through MontePython). 

Is there any way we can arrange a small call so that I can share and get help regarding the technical aspects of the code? or if there is an email I can mail my specific issue to? 

Thank you, 
Meera

**Comment by ThomasTram** [comment]
Hi, what value of `Gamma_dcdm` are you using?

Cheers,
Thomas

**Comment by astrogirl1** [comment]
Hi Thomas, 
I have introduced this new parameter, which is the inverse of Gamma_dcdm : tau. So I supplied tau to be 0.2 thus making Gamma = 5.0. 
This is the part where I have added that change : 

```
  /* dcdm */
  if (pba->has_dcdm == _TRUE_) {
    /* Pass value of rho_dcdm to output */
    pvecback[pba->index_bg_rho_dcdm] = pvecback_B[pba->index_bi_rho_dcdm];
    rho_tot += pvecback[pba->index_bg_rho_dcdm];
    p_tot += 0.;
    rho_m += pvecback[pba->index_bg_rho_dcdm];
    pba->Gamma_dcdm = 1 / pba->new_tau_var;
  }
```

I have also changed the background equations that I am interested in and removed the _index_bi_a_ variable from the following, but reading the manual, I think I should not do that. 
```

if (pba->has_dcdm == _TRUE_) {
    /** - compute dcdm density \f$ d\rho/dloga = -3 \rho - \Gamma \rho \f$*/
    dy[pba->index_bi_rho_dcdm] = -3.*pvecback[pba->index_bg_H]*y[pba->index_bi_rho_dcdm] - pba->Gamma_dcdm*y[pba->index_bi_rho_dcdm];
  }

  if ((pba->has_dcdm == _TRUE_) && (pba->has_dr == _TRUE_)) {
    /*printf("frac = %f", pba->frac_rm_energy);*/
    /** - Compute dr density \f$ d\rho/dloga = -4\rho - epsilon\Gamma \rho \f$ */
    dy[pba->index_bi_rho_dr] = -4.*pvecback[pba->index_bg_H]*y[pba->index_bi_rho_dr]+pba->frac_rm_energy*pba->Gamma_dcdm*y[pba->index_bi_rho_dcdm];
  }
```

Thanks!
Meera

**Comment by ThomasTram** [comment]
Hi again

I think you need to read and assign the value of Gamma_dcdm already in the input module if you are not already doing that. (In the above, it looks like you are only updating Gamma_dcdm from `pba->new_tau_var` in the derivative function, but Gamma_dcdm is used in a few places outside of this function.

However, the main problem is that you pulled the new version of CLASS which now integrates in log(a) instead of conformal time. Because you modified these two lines before the pull, git stated a conflict. Thus, you should update the two equations of motions accordingly. (I think you just need to remove all the `pvecback[pba->index_bg_H]`, but check for yourself.)

Cheers,
Thomas
