### ISSUE TITLE
Running Class on Windows 10

### ISSUE THREAD

**Issue by GaNesHo3** [lesgourg/class_public#413]
Hello guys,

Please anyone guide me to running Class on Windows 10. I have Dev C++ and downloaded the makefile in https://github.com/lesgourg/class_public/issues/65#issuecomment-149907959 but it shows this errors when compiling the testKlass
![image](https://user-images.githubusercontent.com/82928710/115507173-5f312e80-a2ae-11eb-94ac-58378cad125f.png)

**Comment by ThomasTram** [comment]
Hi

Just a few alternative suggestions for running CLASS on Windows 10:

1. Use Linux Subsystem for Windows, [WSL2](https://docs.microsoft.com/en-us/windows/wsl/install-win10).
2. Download and install Visual Studio 2019 and create a proper project instead of relying on the Makefile.

These are just alternatives for you if you don't get this to work...

Cheers,
Thomas

**Comment by GaNesHo3** [comment]
Okay, I'll try it out and update you.

**Comment by GaNesHo3** [comment]
Hello Thomas, 

I am sorry for the delayed reply, I was trying, but it turns out there are some problems. I believe this problem can be solved by copy and past .h files from the include folder to the cpp folder. Do you know any tricks on how to run and compile testKlass without copying and pasting .h files ?

![image](https://user-images.githubusercontent.com/82928710/115765855-d9120680-a3d9-11eb-8d2c-97325b76280f.png)

**Comment by GaNesHo3** [comment]
Hello Thomas,

I am sorry for the delayed reply. I have been trying different things. The first compilation is terminated because it could not find class.h which is in the include folder. Then I try to copy it and put it in cpp folder then now it is terminated because it could not find another file quadrature.h which is also in the include folder, it seems I have to copy all the files in the include folder to the cpp folder for it to run. Is there any alternatives that I can make the program to run the include folder itself in the cpp without repeatedly asking for the different files?

![image](https://user-images.githubusercontent.com/82928710/115774985-d9fc6580-a3e4-11eb-94b7-8425a192f030.png)

**Comment by ThomasTram** [comment]
Hi

Yes, you should add the "include" folder into the list of "include folder". It is a setting in the Visual Studio project. Basically it has a list of directories that it will search for .h files in.

Cheers,
Thomas

**Comment by GaNesHo3** [comment]
Oh okay. It successfully ran. Thank you.

But where all the output file stored?
Can program them to open in the Mathematica automatically?

**Comment by ThomasTram** [comment]
I don't know exactly, but there is probably one place where you can specify arguments to the executable, and here you would specify your .ini file. There is probably also a place where you can specify your "working directory" so it knows where to get the .ini file, and there might also be an "output" directory where it will put the executable, class.exe, after compilation.

You could also simply run class.exe, when you find it, from the command line...

**Comment by GaNesHo3** [comment]
Finally with the help of the installation guide in the link https://github.com/lesgourg/class_public/wiki/Installation and with a small tutorial in https://www.youtube.com/watch?v=R22XhKUwzX4 I am able to generate the results and graphs using gnuplot.

But please check the wiki guides that there is **some problem in generating graphs using python**. 

**Importing classy from python and installing pip install numpy and cython still a problem for the latest python version.** 

Thank you.

**Comment by GaNesHo3** [comment]
Hello, 

For details, this is the problems when importing the classy file from python (check the pic). The classy file we are importing is the one in the class/python as shown in the pic? but it is classy.pyx

![image](https://user-images.githubusercontent.com/82928710/116124821-5f3e8d80-a6f7-11eb-8685-fe3ef4c9ab66.png)

**Comment by pstoecker** [comment]
You need to compile the python wrapper via `make classy` (which is automatically done with `make all`) in the base directory of class. The `*.pyx` cannot be understood by python it is a file that is used by cython which will compile the C-code of class into a shared library that can be used within python.

**Comment by GaNesHo3** [comment]
oh okay. But now it showing this error where it could not find python.h

![image](https://user-images.githubusercontent.com/82928710/116127306-3ff52f80-a6fa-11eb-9841-5bb0d5831478.png)

**Comment by GaNesHo3** [comment]
Well, problem solved by apt install python-dev

Thank you.
