### ISSUE TITLE
Error when importing classy

### ISSUE THREAD

**Issue by rodrigovonmarttens** [lesgourg/class_public#416]
I've installed CLASS following all the instructions, but when I try to import classy on python, it returns the following error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/<myuser>/opt/anaconda3/lib/python3.8/site-packages/classy.cpython-38-darwin.so, 2): Symbol not found: _background_at_tau
  Referenced from: /<myuser>/opt/anaconda3/lib/python3.8/site-packages/classy.cpython-38-darwin.so
  Expected in: flat namespace
 in /<myuser>/opt/anaconda3/lib/python3.8/site-packages/classy.cpython-38-darwin.so

Does anyone knows how to fix that please?

**Comment by ShazAlvi** [comment]
Hi, if I am to make a guess some package has not been installed. Have you
installed all the required packages? Also, make sure that you compile CLASS
in the conda environment that you are using (I am judging by the path that
you are working in a conda environment).

**Comment by rodrigovonmarttens** [comment]
Many thanks, @ShazAlvi !

Actually, I've been able to solve this issue by pointing out the gcc installed with brew in the gcc entry on the Makefile.
