### ISSUE TITLE
Memory leak in HyRec

### ISSUE THREAD

**Issue by adematti** [lesgourg/class_public#421]
Hi,
Running class with valgrind made me notice (i think) a memory leak in HyRec.
atomic->logAlpha_tab[2] and atomic->logAlpha_tab[3] are created in https://github.com/lesgourg/class_public/blob/4724295b527448b00faa28bce973e306e0e82ef5/external/HyRec2020/hydrogen.c#L154
but not freed in https://github.com/lesgourg/class_public/blob/4724295b527448b00faa28bce973e306e0e82ef5/external/HyRec2020/hydrogen.c#L257
Freeing these arrays, the memory leak is resolved and CLASS runs smoothly.
Best

**Comment by ThomasTram** [comment]
Hi

Thanks a lot for reporting this, indeed that is a memory leak! We already fixed it last week, and it will be part of the next minor release, 3.0.2. I will leave the issue open until it has been released.

Cheers,
Thomas

**Comment by adematti** [comment]
Thanks a lot!
Best,
Arnaud

**Comment by adematti** [comment]
3e2641558c518145acfca3fc795e736771fd3bce solved this issue; thanks again! Closing.
