### ISSUE TITLE
tensor-to-scalar power spectrum ratio

### ISSUE THREAD

**Issue by gaby7646** [lesgourg/class_public#422]
Hi! 
I'm trying to include the tensor-to-scalar power spectrum parameters in my .ini file, and the following warning appears:
***[WARNING: input line not recognized and not taken into account: 'r=1.']***
***[WARNING:_ input line not recognized and not taken into account: 'n_t=scc']***
***[WARNING: input line not recognized and not taken into account: 'alpha_t=scc']***

What is the correct way to include them if I want to change the default values?

**Comment by ShazAlvi** [comment]
Can you include your ini file here?

**Comment by pstoecker** [comment]
Have you included `modes = t` in your input? Otherwise CLASS will not read inputs that are relevant for the tensor perturbations.

**Comment by gaby7646** [comment]
> Have you included `modes = t` in your input? Otherwise CLASS will not read inputs that are relevant for the tensor perturbations.

It was. I hadn't included the tensor modes.
