### ISSUE TITLE
How to get temperature-density spectra with classy?

### ISSUE THREAD

**Issue by Ferrangelo** [lesgourg/class_public#427]
Hi everyone, I'm trying to obtain the Temperature-Density power spectra with classy but I'm unable to do it. I am currently using class 2.7 but I've encountered this problem also in class 2.9 and in the last version. 

My issue is that while I get density-density as expected, that is one spectra for each bin plus the spectra in adjacent bins as requested, for the TD I only get one array with a list of numbers, and I have no idea what that array is. Is there a way to get to understand this output or to obtain the TD spectra in a fashion similar to the output file?

this is a minimal example of what I'm doing in classy

```
from classy import Class

common_settings = { 
                    'output' : 'tCl, pCl, nCl',
                    'l_max_lss':500,
                    'selection' : 'gaussian',
                    'selection_mean' : '0.98, 0.99, 1.0',
                    'selection_width' : '0.1',
                    'non_diagonal' :'1'
}


M = Class()
M.set(common_settings)
M.compute()
```

and if I then try with `M.density_cl()` i get something like this:
```
{'dd': {0: array([0.00000000e+00, 0.00000000e+00, 1.44189103e-06, 1.52929787e-06,
         1.62415390e-06, ... , 2.10780586e-07,
         2.09800554e-07]),
  1: array([0.00000000e+00, 0.00000000e+00, 1.42489990e-06, 1.51081772e-06,
         1.60409983e-06, ... , 2.09992650e-07,
         2.09011379e-07]),
  2: array([0.00000000e+00, 0.00000000e+00, 1.41937333e-06, 1.50396963e-06,
         1.59587873e-06, ... , 2.10267447e-07,
         2.09280581e-07]),
  3: array([0.00000000e+00, 0.00000000e+00, 1.40282579e-06, 1.48599564e-06,
         1.57639477e-06, ... , 2.09502494e-07,
         2.08515555e-07]),
  4: array([0.00000000e+00, 0.00000000e+00, 1.39756574e-06, 1.47946957e-06,
         1.56855145e-06, ... , 2.09795466e-07,
         2.08804139e-07])},
 'td': array([0.00000000e+00, 0.00000000e+00, 2.28905418e-09, 1.59427297e-09,
        1.20495625e-09, ... , 2.10033554e-14,
        2.08344533e-14]),
 'ell': array([  0,   1,   2,   3,   4,   5,   ... , 500])}
```

**Comment by ShazAlvi** [comment]
Hi Angelo,
As I remember from my experience, it's the spectra of the first bin indicated by the bin means that you specified. I could not understand how to get the spectra for the remaining bins. The only workaround that I could find, to get the td power spectra for all bins of my concern was to make one instance for each bin. Which I think is not an elegant way of doing things. 

I had open an issue (#385) that has some comments on this which might be useful.

Hope this helped. Please let us know if you find a solution to this problem.

**Comment by Ferrangelo** [comment]
Thank you @ShazAlvi, this helps but still if one has to use several instances of class it's probably easier to directly run the code normally without bothering to use classy.

**Comment by ThomasTram** [comment]
Hi both

Temperature-density correlations are commented out of the code by default:
https://github.com/lesgourg/class_public/blob/4724295b527448b00faa28bce973e306e0e82ef5/source/harmonic.c#L503-L518
I guess you are uncommenting this section in your versions then, and taking the comment into account?

The next step is then the wrapper: the missing correlations are a bug, but it is easily fixed. Change this line
https://github.com/lesgourg/class_public/blob/4724295b527448b00faa28bce973e306e0e82ef5/python/classy.pyx#L685
to
```python
cl[elem] = np.zeros((lmax+1, self.hr.d_size), dtype=np.double)
```
this line
https://github.com/lesgourg/class_public/blob/4724295b527448b00faa28bce973e306e0e82ef5/python/classy.pyx#L700
to
```python
for index in range(self.hr.d_size):
    cl['td'][ell, index] = dcl[self.hr.index_ct_td+index]
```
and this line
https://github.com/lesgourg/class_public/blob/4724295b527448b00faa28bce973e306e0e82ef5/python/classy.pyx#L702
to
```python
for index in range(self.hr.d_size):
    cl['tl'][ell,index] = dcl[self.hr.index_ct_tl+index]
```

Cheers,
Thomas

**Comment by Ferrangelo** [comment]
Hi @ThomasTram Thank you very much that was it. 

To have the same structure as 'dd' array I slightly modified your solution, if you can confirm that it's fine (it seems fine to me from the outputs), I am done. Thanks again.

Modified

https://github.com/lesgourg/class_public/blob/4724295b527448b00faa28bce973e306e0e82ef5/python/classy.pyx#L683-L685

to

```
for elem in ['td', 'tl']:
            if elem in spectra:
                cl[elem] = {}
                for index in range(self.hr.d_size):
                    cl[elem][index] = np.zeros(lmax+1, dtype=np.double)
```
and then, modified

https://github.com/lesgourg/class_public/blob/4724295b527448b00faa28bce973e306e0e82ef5/python/classy.pyx#L699-L702

to

```
if 'td' in spectra:
    for index in range(self.hr.d_size):
        cl['td'][index][ell] = dcl[self.hr.index_ct_td+index]
if 'tl' in spectra:
    for index in range(self.hr.d_size):
        cl['tl'][index][ell] = dcl[self.hr.index_ct_tl+index]

```

**Comment by ThomasTram** [comment]
Hi @Ferrangelo 

That looks good yes!

Cheers,
Thomas
