### ISSUE TITLE
Can't finish compile the python wrapper

### ISSUE THREAD

**Issue by savero12** [lesgourg/class_public#435]
Hello everyone! I would install class in my virtual machine with ubuntu latest version (v.20) but I got an error that said there is no such a file directory named libgfortran.so.1. I already installed the gfortran on my ubuntu, but still have the same proble. What should I do? Thank you
![IMG-0993 (1)](https://user-images.githubusercontent.com/78658709/129466421-0f9dd5b4-4d33-4423-be59-ea5d87b263f1.JPG)

**Comment by ShazAlvi** [comment]
Can you check if the file that it needs is actually in the directory where it is trying to find? This can happen in the case of environments (that the file is installed in a place and CLASS is looking for it in another place).
