### ISSUE TITLE
Computing two-point angular correlation function

### ISSUE THREAD

**Issue by evanbiederstedt** [lesgourg/class_public#44]
I am struggling to use CLASS to directly compute and plot the two-point temperature correlation function C(theta). (See for example first-year WMAP release, astro-ph/0302207v3.pdf, equations (5) and (6) in Section 7. Full derivation found in Durrer 2008 textbook "The Cosmic Microwave Background", equation 2.240.) The measured quantity was released as a WMAP first-year data product. I would like to plot the theoretical prediction C(theta) versus theta.

Naturally, I can manipulate the CLASS-generated outputs C_l and ell in order to calculate this expression. I could then convert ell values into theta, and plot the results. However, I would ideally like to directly *compute* C(theta) using Boltzmann codes. Is there a method to do this with CLASS? Thanks for the help, and thank you for maintaining this *excellent* code!

**Comment by ThomasTram** [comment]
Hi Evan,
thanks for using our code. The temperature correlation is computed directly in multipole space, since the angular dependence is expanded in Legendre multipoles at the level of the Boltzmann equation. This is *much* more efficient than discretising the angular dependence directly. However, from your equation (6) it is of course trivial to compute and plot the angular correlation function; it's a few lines with python using the CLASS wrapper:
````
import numpy as np
from classy import Class
from numpy.polynomial.legendre import legval
cosmo = Class()
cosmo.set({'output':'lCl, tCl','lensing':'yes'})
cosmo.compute()
rcl = cosmo.raw_cl()
lcl = cosmo.lensed_cl()
theta = np.linspace(0,pi,1000)
rCtheta = legval(cos(theta),(2.*rcl['ell']+1.)*rcl['tt']/(4.*np.pi))
lCtheta = legval(cos(theta),(2.*lcl['ell']+1.)*lcl['tt']/(4.*np.pi))
````
![cltheta](https://cloud.githubusercontent.com/assets/5593952/7469690/5a7f1650-f30e-11e4-886e-d3c85bdbd571.png)

**Comment by evanbiederstedt** [comment]
Hi Thomas, 

It appears I never got back to you on GitHub to say thanks for the help. So, thanks!

I have one more question for you regarding your plot of two-point correlation function. When I run via the Python wrapper:

     import numpy as np
     from classy import Class
     import matplotlib.pyplot as plt 
     from numpy.polynomial.legendre import legval
     cosmo = Class()
     cosmo.set({'output':'lCl, tCl','lensing':'no'})
     cosmo.compute()
     rcl = cosmo.raw_cl()
     theta = np.linspace(0,np.pi,1000)
     rCtheta = legval(np.cos(theta),(2.*rcl['ell']+1.)*rcl['tt']/(4.*np.pi))
     deg = np.degrees(theta)
     plt.plot(deg, rCtheta)

my output plot looks something like:

![wdodw6oi2zvugaaaabjru5erkjggg -1](https://cloud.githubusercontent.com/assets/6968193/8840162/6dd17ba0-30ab-11e5-803d-4eb25922858b.png)

Could I ask you what you are plotting `rCtheta` against to get the distinct curve from theta=20 to theta=80 on your plot? 

Apologies again for the late reply

**Comment by ThomasTram** [comment]
Hi,

you just need to adjust your y-limits:
````
plt.ylim([-1e-10,5e-10])
````

Then your plot is the same as mine.
