### ISSUE TITLE
Label issue with transfer functions

### ISSUE THREAD

**Issue by emiliobellini** [lesgourg/class_public#442]
Hi all,
I think there is a label inconsistency in the transfer functions output.
The name of the k column is called "k (h/Mpc)", but then the values that are stored there are k_over_h.
In the current class version these are at lines 220 and 316

Best wishes,
Emilio

**Comment by ThomasTram** [comment]
Hi Emilio

It is correct as it is, since (h/Mpc) denotes the *unit* of k, it is not a multiplicative factor. If you got k in units of Mpc, and you wish to express k in units of h/Mpc you must of course divide k by h as you say.. 

Cheers,
Thomas

**Comment by emiliobellini** [comment]
Hi Thomas,
you are absolutely right! My bad.. :)

Cheers,
Emilio
