### ISSUE TITLE
Step size too small error

### ISSUE THREAD

**Issue by Zixuan-phy** [lesgourg/class_public#443]
Hi all,

I am testing some kind of decaying dark matter that evolves in stages, and I added piecewise differential equations to background_derivs. But the following error occurred:

![stepsize_error](https://user-images.githubusercontent.com/90609355/133188113-8d8c72d7-6ae5-4e6c-9f39-aba11379b4c2.png)

Is it because the function is not smooth? Are there other ways to integrate piecewise differential equations?

Thanks a lot!
Zixuan

**Comment by ajcosmology** [comment]
Hello,
Is the error resolved?
If yes, how?

Thanks.
Alex
