### ISSUE TITLE
error; incomprehensible input for the field 'fluid_equation_of_state'

### ISSUE THREAD

**Issue by Rockdeldiablo** [lesgourg/class_public#456]
Hi, i am was trying to add a new equation of state to class and i thought i had modified everything i needed but apparently i didn't.
In order, in the ini file:
1) i commented Omega_fld
`#Omega_fld = 0
Omega_scf = 0
Omega_Lambda = 0.7`
2) i changed the variables associated to the EoS ( made up values for now):
```
fluid_equation_of_state = LRS

w0_fld = -0.9
wa_fld = 0.1
```
in the background.c i added the  3 case LRS for   
    *dw_over_da_fld , *w_fld  and     *integral_fld  

but when i try  to run 

> ./class lrs.ini
 i get:

> Reading input parameters
>  -> matched budget equations by adjusting Omega_fld = -0.009974
> 
> 
> Error running input_init 
> =>input_init(L:78) :error in input_read_from_file(&fc,ppr,pba,pth,ppt,ptr,ppm,phr,pfo,ple,psd,pop, errmsg);
> =>input_read_from_file(L:426) :error in input_read_parameters(pfc,ppr,pba,pth,ppt,ptr,ppm,phr,pfo,ple,psd,pop, errmsg);
> =>input_read_parameters(L:1531) :error in input_read_parameters_species(pfc,ppr,pba,pth,ppt, input_verbose, errmsg);
> =>input_read_parameters_species(L:2931) :error; incomprehensible input 'LRS' for the field 'fluid_equation_of_state'

is there anything else that i have to modify?

**Comment by lesgourg** [comment]
Hi @Rockdeldiablo, I see potentially two issues here:
1) if you use a DE fluid you probably want to set first Einstein's cosmological constant to zero. Then your input file should have 'Omega_Lambda=0'
2) if you want to use a new type of e.o.s called LRS, you should declare it first in include/background.h:
enum equation_of_state {CLP,EDE,LRS};

**Comment by Rockdeldiablo** [comment]
ah you right on both points, i completely missed them, especially Omega_lambda, but i keep getting the same error
Reading input parameters
 -> matched budget equations by adjusting Omega_fld = 0.690026

> 
> Error running input_init 
> =>input_init(L:78) :error in input_read_from_file(&fc,ppr,pba,pth,ppt,ptr,ppm,phr,pfo,ple,psd,pop, errmsg);
> =>input_read_from_file(L:426) :error in input_read_parameters(pfc,ppr,pba,pth,ppt,ptr,ppm,phr,pfo,ple,psd,pop, errmsg);
> =>input_read_parameters(L:1531) :error in input_read_parameters_species(pfc,ppr,pba,pth,ppt, input_verbose, errmsg);
> =>input_read_parameters_species(L:2931) :error; incomprehensible input 'LRS' for the field 'fluid_equation_of_state'

maybe it's something i did in the background.c file since i  don't know c  and i just emulated what  i have seen for clp:
```
  case LRS:
      *w_fld = pba->w0_fld - pba->wa_fld * (1. - a)/a;
      break;

```
```
  case LRS:
    *dw_over_da_fld = - pba->wa_fld/(a*a);
    break;
```
```
  case LRS:
    *integral_fld = 3.*(  1. -log(a) -  pba->w0_fld* log(a) -1/a   -  pba->wa_fld*log(a)   );
    break;
```

**Comment by Rockdeldiablo** [comment]
looks like i was able to solve the issue , i had to update the input.c file.

**Comment by lpttprnc** [comment]
> looks like i was able to solve the issue , i had to update the input.c file.

Hello @Rockdeldiablo I face the same problem. What update did you do to the input.c? thank you
