### ISSUE TITLE
non-linear matter power specra of CLASS and CAMB

### ISSUE THREAD

**Issue by 0satoken** [lesgourg/class_public#46]
Hi all,
I have used CAMB so far and started using CLASS.
I compared matter power spectra generated by both codes.
The linear matter power spectra agree quite well but the problem is that non-linear matter power spectra are inconsistent with each other and the difference reaches about 10% at most.
Attached figures show the result, where I adopted WMAP 9 year cosmology and no massive neutrinos.
I have checked that both codes employ the same HaloFit of Takahashi et al. (2012).
The version of CLASS I used is 2.4.3 and CAMB is January 2015.
![pk](https://cloud.githubusercontent.com/assets/9446410/7718921/d4fee212-fef2-11e4-8ced-d80897cfb493.png)
![pk_nl](https://cloud.githubusercontent.com/assets/9446410/7718923/d743a71a-fef2-11e4-86c7-72b3571f1d21.png)

**Comment by oscarhdz7** [comment]
Hello,
I am wondering if you have made any progress on this issue? I too have seen that the linear power spectra agree but I have seen an even more dramatic difference between the CLASS and CAMB nonlinear power spectrum at nonzero redshifts. I have using CLASS 2.4.3 to get the non-linear matter power spectrum between z=0 and z=5 with the precision file pk_ref.pre and for z>3 the CLASS linear and nonlinear power spectrum are identical up to k=8 h/Mpc. CAMB does produce different nonlinear and linear power spectrum for z>3. A couple days ago I opened up the issue "halofit with z>3", regarding this problem.
Regards,
Oscar

**Comment by 0satoken** [comment]
Hello,
In the pull request #81 , this issue is resolved and I also have confirmed that the non-linear power spectra computed by CAMB and CLASS in the latest version are consistent with each other. I close this issue.
Regards,
Ken
