### ISSUE TITLE
output: transfer function cdm density

### ISSUE THREAD

**Issue by sdoors** [lesgourg/class_public#48]
Hi,

just a quick question I've failed to figure out. I want to know the cmd density transfer function  T at z=1000. I define T as follows:

(delta rho/rho)_{z=1000} = T (delta rho/rho)_0

The output of CLASS is obviously not T, but might be something like const.*(k^n * T* (-1)^m) for some n,m. Can you tell me how I get T from the output of CLASS?

Thank you very much in advance.

**Comment by ThomasTram** [comment]
Hi,

the output of CLASS is really just (delta rho/rho)(k). If you run with with the .ini ````trsf.ini'''' file:
````
output = dTk
z_pk = 0.0, 1000.0
````
you will get two files, ````output/trsf00_z0_tk.dat'''' and ````output/trsf00_z1_tk.dat''''. The header in the z0 files reads:
````
# Transfer functions T_i(k) for adiabatic (AD) mode (normalized to initial curvature=1) at redshift z=0
# for k=1.045e-05 to 0.630176 h/Mpc,
# number of wavenumbers equal to 561
# d_i   stands for (delta rho_i/rho_i)(k,z) with above normalization 
# d_tot stands for (delta rho_tot/rho_tot)(k,z) with rho_Lambda NOT included in rho_tot
# (note that this differs from the transfer function output from CAMB/CMBFAST, which gives the same
#  quantities divided by -k^2 with k in Mpc^-1; use format=camb to match CAMB)
#
#    1:k (h/Mpc)              2:d_g                    3:d_b                    4:d_cdm                  5:d_ur                   6:d_tot              
````
You can also request velocity transfer functions by specifying vTk along with dTk. Note that you will only be able to chose redshifts z from after recombination with the above .ini file. If you want earlier transfer functions you just need to add ````tCl```` to the list of outputs. (Sources are normally only computed after recombination if tCl's are not requested.)

Cheers,
Thomas

**Comment by sdoors** [comment]
Thanks a lot Thomas for the prompt answer, I understand!
I've tried to generate output for the settings (high redshifts)

output = tCl, dTk
z_pk = 1e3, 1e4

which generates an error. It seems z=1e4 is too high. Is there any chance to get (delta rho/rho) for high redshifts, say 1e4, 1e5, 1e6 (where is the limit)?

**Comment by ThomasTram** [comment]
Hi again

if you set
````start_sources_at_tau_c_over_tau_h = 0.0006````
you can go down to approximately z=9000. If you decrease the parameter further, it will complain that you need to reduce ````recfast_z_initial````. The reason is clear: the perturbations module require a thermodynamics history over its entire range. However, decreasing ````recfast_z_initial```` has to be compensated by an increase in the sampling parameter ````recfast_Nz0````. Since RECFAST uses a linear sampling, increasing ````recfast_z_initial```` from 1e4 (default) to 1e5 will require you to increase ````recfast_Nz0```` from 20,000 (default) to 200,000.

However, there is usually no point in pushing the code to even smaller redshifts since for any reasonable k-range, all modes will be outside horizon and you are basically just getting the initial conditions. (e.g. you can use Eq. 96 and Eq 98 from Ma & Bertschinger http://arxiv.org/pdf/astro-ph/9506072.pdf) for these redshifts.

**Comment by sdoors** [comment]
Thanks again for your answer. I've just two last and brief questions: 

1)Where do I have to change these params. Just in the .ini file like

output = tCl, dTk
z_pk = 1e5, 1e4
recfast_Nz0 = 200000
recfast_z_initial = 1e5

This produces an error. 

2) Is it possible to extract the used initial conditions to check, e.g. the differences between the output at z=1e5 and initial conditions ?

Cheers & thanks a lot for answering!

**Comment by ThomasTram** [comment]
The .ini file yes. You forgot to also decrease the initial time of source sampling by changing ````start_sources_at_tau_c_over_tau_h````. For instance, the following .ini file can give you the transfer function down to approximately z = 9e4:
````
output = dTk, tCl
z_pk = 0.0, 1100.0, 9e3, 9e4
start_sources_at_tau_c_over_tau_h = 0.00005
recfast_Nz0 = 200000
recfast_z_initial = 1e5
````

Regarding the initial conditions, you can read them off from the code, they are found in ````perturb_initial_conditions()```` You can get background and thermodynamic quantities by using the wrapper or by setting ````write background = yes```` and ````write thermodynamics = yes````. You could also output individual perturbations as a function of time for specific k-values using ````k_output_values = 0.001, 0.01, 0.1````. Note that the output of the perturbations are transformed into Newtonian gauge, so if you want to compare with the density transfer functions, it is best to change gauge to Newtonian by using ````gauge = Newtonian````. On the other hand, the initial conditions in the code are written in synchronous gauge, so if you go that way it is easier to stick with synchronous which is the default.

Cheers,
Thomas

**Comment by sdoors** [comment]
Thank you!

**Comment by sdoors** [comment]
Hi,
hopefully the very last question, sorry: I don't understand the normalization of the output. For example, the ratio 

(delta rho/rho)_{z=1000} / (delta rho/rho)_{z=9e4}

should be 1 for largest scales which haven't entered the horizon, right? It is however of order 1e3. I guess it is normalized by a redshift dependent term (maybe involving sigma_8(z) in some way)? Could you tell me this normalization (output files states: normalized to initial curvature=1. I do not understand this)?

Cheers

**Comment by ThomasTram** [comment]
Why do you think the ratio should be 1 at large scales? If you look at the synchronous gauge initial conditions Eq. 96 in Ma & Bertschinger, we get directly that 
delta_i(tau1)/delta_i(tau2) = tau1^2/tau2^2.

Remember that delta_i is gauge dependent: In Newtonian gauge we find indeed that delta_i is constant outside horizon. Look at Eq. 98 of M&B, and you can try yourself by rerunning CLASS using ````gauge=Newtonian````.

**Comment by sdoors** [comment]
Of course - I thought in the wrong gauge :-)
