### ISSUE TITLE
A weird kink in CLASS matter power spectrum

### ISSUE THREAD

**Issue by yicizhong98** [lesgourg/class_public#488]
Hi! I'm currently using CLASS to generate matter power spectrum, but it appears a **weird kink at low \ell** (please see the figure attached below
![download-1](https://user-images.githubusercontent.com/58408970/178184973-0a19964c-0688-4656-9a3f-ed67e3d77cb2.png)
), which is not within our expectation...I'm kind of wondering if you have any idea of where it comes from, and how to resolve it?

Thanks in advance,
Yici

P.S., Here is my python code to generate this matter power spectrum:

> OmegaB = 0.0486 
> OmegaM = 0.2603
> h=0.6774
> ombh2 = OmegaB*h**2
> omch2 = OmegaM*h**2
> sigma8 = 0.8159
> n_s = 0.9667 
> 
> z1 = 0.11111111111111116
> z2 = 0.09890109890109877
> z_s = (z1 + z2)/2
> lmax = 12288
> 
> LambdaCDM = Class()
> LambdaCDM.set({'omega_b':ombh2,'omega_cdm':omch2,'h':h,'sigma8':sigma8,'n_s':n_s})
> 
> LambdaCDM.set({'output':'mPk,nCl',
>                'lensing':'no',
>                'P_k_max_1/Mpc':100.0,
>                'z_pk':0.0,
>                'reio_parametrization':'reio_camb',
>                'selection':'tophat',
>                'selection_mean':z_s,
>                'selection_width': (z1-z2)/2, 
>                'l_max_lss':lmax, 
>                'non linear':'halofit'
>               })
> LambdaCDM.compute()
> cls2=LambdaCDM.density_cl(lmax)
> ell_th=cls2['ell'][2:]
> cldd_th=cls2['dd'][0][2:]
> plt.loglog(ell_th,cldd_th,label='Classy theory')
> plt.xlabel('$\ell$')
> plt.ylabel('cldd')
> plt.legend()

**Comment by kcroker** [comment]
If this fixed your issue @yicizhong98 , could you please Close it?

**Comment by yicizhong98** [comment]
Thanks!! That fixed everything. Sorry that I forgot to close it.
