### ISSUE TITLE
sigma8 output

### ISSUE THREAD

**Issue by hsxavier** [lesgourg/class_public#49]
Hello,

Is it possible to make CLASS output the value of sigma8 given an .ini file?

Thanks,
Henrique

**Comment by Andromedanita** [comment]
I found an easy way to check its value is to calculate it using the equation for sigma(R) from the power spectrum output: 

![screen shot 2015-06-04 at 11 30 53 am](https://cloud.githubusercontent.com/assets/4367142/7987780/9c82f4c0-0aad-11e5-9576-aed376dcf977.png)

Where R=8 h-1Mpc

**Comment by miguelzuma** [comment]
CLASS will print the value of sigma_8 if you:
- ask for the matter power spectrum (output = mPk)
- set spectra_verbose to 1 or higher (spectra_verbose = 1)

The value of sigma_8 is computed and printed is after line 2669 of spectra.c

**Comment by hsxavier** [comment]
Great, thanks!
