### ISSUE TITLE
Background_init error from free(pvecback)

### ISSUE THREAD

**Issue by joshuaange** [lesgourg/class_public#496]
In trying to run CLASS with varying values for alpha and me, this error occurs:

> Error running background_init 
> =>background_init(L:822) :condition (pba->shooting_failed == _TRUE_) is true; Shooting failed, try optimising input_get_guess(). Error message:
> 
> input_shooting(L:653) :error in input_find_root(&xzero, &fevals, ppr->tol_shooting_deltax_rel, &fzw, errmsg);
> =>input_find_root(L:930) :error in input_fzerofun_1d(x1, pfzw, &f1, errmsg);
> =>input_fzerofun_1d(L:1003) :error in input_try_unknown_parameters(&input, 1, pfzw, output, error_message);
> =>input_try_unknown_parameters(L:1383) :error in thermodynamics_init(&pr,&ba,&th);
> =>thermodynamics_init(L:360) :error in thermodynamics_checks(ppr,pba,pth);
> =>thermodynamics_checks(L:704) :condition ((pth->YHe < _YHE_SMALL_)||(pth->YHe > _YHE_BIG_)) is true; Y_He=-21.1258 out of bounds (0.01<Y_He<0.5)
> getting deriv w.r.t. omega_c_h2

As far as I can tell, it's because in thermodynamics.c, line 523 has `free(pvecback)` and line 668 then tries to find its value with `pvecback[pba->index_bg_varc_alpha]`. Moving the `free(pvecback)` to line 678 (after the other deallocation) seemingly fixes the issue.

Note: this was done in modified CLASS https://github.com/selimhotinli/class_delens merged with class_public, but I don't think that's playing a role

**Comment by schoeneberg** [comment]
Dear @joshuaange, I implemented the solution in the git release pipeline, and hopefully it will be published relatively soon!
