### ISSUE TITLE
Adding non-smooth background functions 

### ISSUE THREAD

**Issue by dblaste** [lesgourg/class_public#50]
Hi!

I am trying to work with a background function which I want to set to a particular value after it reaches this value dynamically. For instance, if my function is f=X, I want to assign 

if(X<=0) {f=0;}
else{f=X;}

However, this does not seem to be possible in general. Notice that this will make the function continuous, but not smooth. The code often says 

Error in perturb_init 
=>perturb_init(L:363) :error in perturb_solve(ppr, pba, pth, ppt, index_md, index_ic, index_k, pppw[thread]);
=>perturb_solve(L:2382) :error in generic_evolver(perturb_derivs, interval_limit[index_interval], interval_limit[index_interval+1], ppw->pv->y, ppw->pv->used_in_sources, ppw->pv->pt_size, &ppaw, ppr->tol_perturb_integration, ppr->smallest_allowed_variation, perturb_timescale, ppr->perturb_integration_stepsize, ppt->tau_sampling, tau_actual_size, perturb_sources, perhaps_print_variables, ppt->error_message);
=>evolver_ndf15(L:474) :error in new_linearisation(&jac,hinvGak,neq,error_message);
=>new_linearisation(L:967) :condition (funcreturn == _FAILURE_) is true; Failure in sp_ludcmp. Possibly singular matrix!

Even if this function is not used in the perturbation module, one gets the previous complaint. If the discontinuity in the derivative is not big, the error goes away.

I was thinking about smoothing the transition by a regularized Heaviside function, but before I was wondering if there is another way to  do it.

Thanks a lot!

Diego

**Comment by lesgourg** [comment]
Hi Diego,
There is no way to do anything with a background function that is not continuous and derivable... you must arrange for a smooth transition!

**Comment by dblaste** [comment]
Thank!

**Comment by dblaste** [comment]
The solution I found (which is not perfect) is to run the code twice. First time I run the code without modification and write the time at which f=0, t0. The second run, the code knows that t0\neq 0 and then instead of computing f computes f Heaviside (-(t-t0)), where the Heaviside is regularized with a tanh. Notice that using directly  f Heaviside(f) is not trivial, since the tanh (or other regularizations I know) require that the argument of the Heaviside is monotonic. 

The method is not perfect, because t0 is not exactly the place where the run with the regularized Heaviside will cancel. Still, it seems that I can make the transition quite steep, and the code runs.

**Comment by ThomasTram** [comment]
Hi Diego,

one could also try a dynamic approach: Instead of solving
y' = f(t,y)
you solve
y' = f(t,y) * (1-(y/y_eq)^n )
where y_eq is the equilibrium value/solution that you want to track eventually. The ODE will be equivalent to the one you are solving now for y<y_eq but it will have a solution y=y_eq. If y can be negative, maybe it is better to do
y' = f(t,y) * (1-abs(y/y_eq)^n )

Maybe it will work.

Cheers,
Thomas

**Comment by dblaste** [comment]
Thanks Thomas. 

I could try this, but then I need to make f a dynamical variable (for the moment, it is a derived background quantity). Let me think about it. 

y'=F(y,f
