### ISSUE TITLE
Discrepancy between Class 2018 baseline and Planck 2018 bestfit at low \ell

### ISSUE THREAD

**Issue by matteotagliazucchi** [lesgourg/class_public#501]
Hi everyone.

I've computed CMB power spectra by using the 2018 baseline Planck file _base_2018_plikHM_TTTEEE_lowl_lowE_lensing.ini_ already contained in Class.  Then I plotted the residuals with respect to Planck binned experimental data (contained in the second column of the file _COM_PowerSpect_CMB-TT-binned_R3.01.txt_  available [here]( http://pla.esac.esa.int/pla/aio/product-action?COSMOLOGY.FILE_ID=COM_PowerSpect_CMB-TT-binned_R3.01.txt) ).

To compute the residuals I've interpolated the Class output and evaluated the interpolated function on the same \ell provided in the Planck file. 
Then I took the difference between these values and the Planck experimental binned data.
The result, including also the errorbars contained in column 2 and 3 of  _COM_PowerSpect_CMB-TT-binned_R3.01.txt_ , is
![Screenshot from 2022-11-08 14-39-37](https://user-images.githubusercontent.com/60974922/200579633-dc5206e1-c934-4349-814e-8c78f8d2be4a.png)

I expect these residuals to be similar to those obtained by subtracting the experimental Planck binned data and the Planck bestfit points (fifth column of  _COM_PowerSpect_CMB-TT-binned_R3.01.txt_  ).

Unfortunately, this is not true.
The plot in this case looks like
![Screenshot from 2022-11-08 14-43-30](https://user-images.githubusercontent.com/60974922/200580496-d99ed434-1322-4c05-884c-9e021b3a3769.png)

Clearly, at small \ell there is a difference in the two plots which is even more clear if I superimpose the two plots
![Screenshot from 2022-11-08 14-55-53](https://user-images.githubusercontent.com/60974922/200583251-e1e8ee88-953e-4e39-b8ed-4a1c08e1de61.png)

The fact that Class baseline does not reproduce well Planck bestift is evident even if one compares directly the two spectra:
![Screenshot from 2022-11-08 14-51-52](https://user-images.githubusercontent.com/60974922/200582358-78a62211-d281-42c1-b10b-53e1e5a37345.png)

Does someone knows why Class baseline does not reproduce well Planck bestifit?

**Comment by schoeneberg** [comment]
Dear @matteotagliazucchi, that might just be the result of using the bestfit file that includes CMB lensing, which is not the same bestfit as in the official Planck file, which to my best knowledge doesn't include lensing. E.g. if I look at the COM_PowerSpect_CMB-base-plikHM-TTTEEE-lowl-lowE-lensing-minimum-theory_R3.01.txt file (which does include lensing), then the low L multipoles differ from COM_PowerSpect_CMB-TT-binned_R3.01.txt. As such, this might already explain the problem :)

**Comment by matteotagliazucchi** [comment]
> Dear @matteotagliazucchi, that might just be the result of using the bestfit file that includes CMB lensing, which is not the same bestfit as in the official Planck file, which to my best knowledge doesn't include lensing. E.g. if I look at the COM_PowerSpect_CMB-base-plikHM-TTTEEE-lowl-lowE-lensing-minimum-theory_R3.01.txt file (which does include lensing), then the low L multipoles differ from COM_PowerSpect_CMB-TT-binned_R3.01.txt. As such, this might already explain the problem :)

Thank you so much for the answer! P
