### ISSUE TITLE
How to make q_size_ncdm smaller?

### ISSUE THREAD

**Issue by ash2223** [lesgourg/class_public#507]
Hello! I was wondering if there’s a way to sample neutrino momenta over a smaller momentum grid, i.e. to make q_size_ncdm = 3 instead of 5 in background.c? I turned on verbose for background and it confirms that this value is 5 in the line “ncdm species i=1 sampled with 11 (resp. 5) points for purpose of background (resp. perturbation) integration”:

![BB5B25C3-239C-45E0-BBE5-9B33874597C9](https://user-images.githubusercontent.com/61329093/213883350-483ce7b5-6c76-4f12-93c0-d51390095a87.jpeg)

I’m trying to find a way to adjust this parameter but it seems like its value is defined in quadrature.c. Not sure if I’m correct about this though. Thank you so much!

-Adam

**Comment by ThomasTram** [comment]
Hi

Just read `explanatory.ini`:
https://github.com/lesgourg/class_public/blob/aa92943e4ab86b56970953589b4897adf2bd0f99/explanatory.ini#L385-L400

Cheers,
Thomas
