### ISSUE TITLE
Meaning of Cls in python wrapper?

### ISSUE THREAD

**Issue by DanBThomas** [lesgourg/class_public#52]
Hey

Quick question:
What are the Cls that are in the dictionary in the python wrapper?

In particular, when lensing is on and adiabatic plus isocurvature modes are being run.
Are they the sum of the different modes plus lensing?
Can I access different Cls through this dictionary, i.e. just isocurvature, lensed or unlensed, etc. If so, is there a list of commands somewhere as to the different possibilities?

I have been looking for the answer in the documentation and couldn't find it; my apologies if I've missed it.

Thanks
Dan

**Comment by ThomasTram** [comment]
Hi,

the Cl's returned from the wrapper function ````raw_cl()```` are the unlensed total Cl while the Cl's returned from the wrapper function ````lensed_cl()```` are the lensed total Cl. Cl's for individuel initial conditions are not available in the wrapper so far, but only when running CLASS from command line.

However, they are in fact computed inside the wrapper, they are just not returned to Python. So adding them should not be too much work.

Cheers,
Thomas

**Comment by DanBThomas** [comment]
Cheers for this! 
Thanks 
Dan 

----- Original Message -----
