### ISSUE TITLE
Undefined reference to 'isinfinite'

### ISSUE THREAD

**Issue by ellisherman** [lesgourg/class_public#53]
When I try to compile class, it throws the error 'undefined reference to 'isinfinite'

Here's the full error: 
build/background.o: In function `background_initial_conditions':
...3/build/../source/background.c:1815: undefined reference to `isfinite'

How can I resolve this?

Thanks!

**Comment by ThomasTram** [comment]
Hi,
which compiler are you using? The ````isfinite()```` macro is part of the C99 specification, so you can try to enable C99 support explicitly by adding ````-std=c99```` to the list of compiler flags. (Assuming that you are using GCC).

Another option is to comment out the offending line in ````background.c```` - it is the only place that the macro is used and it is in the quintessence part of the code. So commenting this test should normally be safe.

Cheers,
Thomas
