### ISSUE TITLE
make: *** [Makefile:195: classy] Error 1

### ISSUE THREAD

**Issue by Hayyim-H** [lesgourg/class_public#532]
During the installation process, when I type the 'make' command, I receive the error:
"Cython.Compiler.Errors.CompileError: /home/hayyim/Descargas/class/python/../python/classy.pyx
 make: *** [Makefile:195: classy] Error 1.'
I don't know how to fix this, as I have python3, cython, numpy, and gcc updated to the latest version.

**Comment by damonge** [comment]
Might be related to #531

**Comment by Hayyim-H** [comment]
> Might be related to #531

Yeah, thaks!
I change the version of Cython and it works
