### ISSUE TITLE
Output correlation functions w(theta) instead/besides Cls

### ISSUE THREAD

**Issue by hsxavier** [lesgourg/class_public#54]
Hello,
In the CLASS documentation it is mentioned that the code can compute the angular correlation functions, but I did not find out how to request this output from the code. I am interested in the auto- and cross-correlation functions of counts and galaxy lensing at different redshifts.
Thanks!

**Comment by ThomasTram** [comment]
Hi,

to us the Cl's *are* the angular correlation functions. If you would like to express them in real (angular) space it is just one line in Python:
https://github.com/lesgourg/class_public/issues/44

Did that answer your question?

Cheers,
Thomas

**Comment by hsxavier** [comment]
Hello,

Yes, thank you.
