### ISSUE TITLE
Output both unlensed C_ell and normalized C_ell, ell(ell+1)/2pi*C_ell

### ISSUE THREAD

**Issue by evanbiederstedt** [lesgourg/class_public#55]
Hi,

My colleagues and I are slightly confused:

The correct command to get the temperature Cl's is cls =
``cls = cosmo.raw_cl()['tt']``
and other Cl's are available by substituting 'tt' bt 'te', 'ee', or 'bb'. If you want a different l_max than the default, you should also pass the parameters ``l_max_scalars`` and ``l_max_tensors``.

The output ``cls = cosmo.raw_cl()['tt']``: is this C_ell or the normalized C_ell, ell(ell+1)/2pi*C_ell? 

Is there a way to output both unlensed C_ell and the normalized C_ell, D_ell =  ell(ell+1)/2pi*C_ell? 

Thanks!

**Comment by ThomasTram** [comment]
Hi Evan,

the wrapper do not normalise the Cls, but constructing them manually is just one line in Python. Note that you conveniently get a numpy array of the corresponding ell-values in the dictionary, just write ````cls['ell']````. You get the lensed Cls from the function ````cosmo.lensed_cl()````.

Cheers,
Thomas

**Comment by evanbiederstedt** [comment]
Thomas, 

Thanks for the clarification.

**Comment by evanbiederstedt** [comment]
Thomas, 

I'm afraid I'm still a bit confused. In the file "explanatory00_cl.dat" in class_public-master/output, the file is headed with comments
""
# dimensionless total [l(l+1)/2pi] C_l's
# for l=2 to 3000, i.e. number of multipoles equal to 2999
""

Does this mean the TT C_ell outputs are C_ell or the normalized C_ell, ell(ell+1)/2pi*C_ell?

**Comment by ThomasTram** [comment]
Both are correct: Cls are multiplied by l(l+1)/(2 pi) in the output files xxx_cl.dat, but not in the wrapper. (This is trivial to check by just plotting the Cls in the explanatory_cl.dat and the Cls from the wrapper). This is to make it easy for users to plot the Cl's from the command line (i.e. using Gnuplot).

**Comment by evanbiederstedt** [comment]
Hi Thomas, 

Thanks for the response. So my understanding is:

Without the Python wrapper (i.e. to compile/use entirely in C), the default output for C_ell (e.g. C^TT_ell) is the "dimensionless total [ell(ell+1)/2pi] C_ell" in file `xxx_cl.dat` (e.g. `test_cl.dat`). 

To change the format to C_ell without the ell(ell+1)/2pi factor, you set `format` to `camb` in the input file, `input.c`, as the factorless C_ell is the CAMB format. And the reason for this choice of format is to plot the power spectra in the command line. Is this correct? 

Now I am unsure of the Python wrapper: the default C_ell's using the Python wrapper are the factorless CAMB C_ells? 
That is, if I use the command in Python 

`cls = cosmo.raw_cl()['tt']`

this outputs the TT C_ell in CAMB format, i.e. without the (ell(ell+1))/2pi factor? (And therefore the conventional thing to do in Python is create the (ell(ell+1))/2pi factor yourself.)

**Comment by ThomasTram** [comment]
Hi,
let me try to make this even more clear then. When you compile CLASS, you will get an executable program called ````class```` and a Python module called ````classy````. You have to ways of using CLASS, either by running from the command line, i.e. ````./class explanatory.ini```` or by using the wrapper. 
In the first case you will get ````explanatoryXX_cl.dat```` and  ````explanatoryXX_cl_lensed.dat````. These are the total Cls *with* the factor l(l+1)/(2 pi), unlensed and lensed respectively, precisely as explained in the header of these files. When you use the wrapper you will get unlensed Cls by calling ````.raw_cl()```` and lensed Cl's by calling ````.lensed_cl()````. Both are *without* the factor.
You can **not** modify this behaviour from the ````.ini````-file, and the option ````camb format```` is related to something entirely different, namely the transfer functions. All this is explained in ````explanatory.ini````.

**Comment by evanbiederstedt** [comment]
Ok, thanks for the clarification. 

So there is no way to output using `class` the C_ells without the factor ell(ell+1)/(2pi), correct? One must use the Python module `classy`.

**Comment by ThomasTram** [comment]
That is correct.

**Comment by evanbiederstedt** [comment]
Ok, I see now. Thanks for the help!
