### ISSUE TITLE
k domain settings for P(k)

### ISSUE THREAD

**Issue by lemiche** [lesgourg/class_public#56]
As far as I could tell the input file only enables to set the maximum k in the domain 
for the power spectrum P(k).

My questions are:
-Is k_min set by default? If so, then how? Does it differ for different input choices?
-How is the k interval or step set in the domain of k?
For example, in the CAMB web interface, one is enabled to set k per log interval for 
transfer functions output. 
 
many thanks in advance!

**Comment by aoifeboyle** [comment]
@lemiche I stumbled across this issue when looking for the same information. I know it's a little old now but did you ever find out how to set the size of the k interval (if it's possible)?

**Comment by ThomasTram** [comment]
There are a few ways to modify the k-sampling:
1) If CMB output is requested, kmin is set to match the largest scale of the CMB.
2) Here is a list of all precision parameters affecting the k-sampling, along with their default values:
````
  ppr->k_min_tau0=0.1;
  ppr->k_max_tau0_over_l_max=2.4; // very relevant for accuracy of lensed ClTT at highest l's
  ppr->k_step_sub=0.05;
  ppr->k_step_super=0.002;
  ppr->k_step_transition=0.2;
  ppr->k_step_super_reduction=0.1;
  ppr->k_per_decade_for_pk=10.;
  ppr->k_per_decade_for_bao=70.;
  ppr->k_bao_center=3.;
  ppr->k_bao_width=4.;
````
All these parameters can be set in the ````.ini```` file using the name listed above. For instance you can add
````
k_per_decade_for_pk=50.
````
This parameter is probably the one you are interested in by the way.

Cheers,
Thomas

**Comment by aoifeboyle** [comment]
@ThomasTram Thank you so much! :)

**Comment by lemiche** [comment]
@ThomasTram Thanks for your response...I was afraid that I won't get an answer for that sometime soon. Yet, I still have some unclear issue regarding the default k_min.
You note the case when CMB output is requested, but I'm requesting only P(k).
Then it does not make sense that the default k_min is 0.1 as noted here above in the list of parameters. What are the units? What am I missing?
Thanks in advance.

**Comment by ThomasTram** [comment]
The parameter ```` ppr->k_min_tau0 ```` is k_{min} * tau_0, so it is dimensionless. tau0 is the conformal age of the Universe which is about 14000Mpc depending on the cosmology. So kmin = 0.1/(14 000Mpc) ~ 7e-6 Mpc^-1. In the output files the unit of k is usually [h/Mpc] so you have an additional Hubble parameter (h ~ 0.7).

**Comment by lemiche** [comment]
Thank you so  very much! :+1:

**Comment by ThomasTram** [comment]
I am glad I could help! Closing the issue...

**Comment by borisbolliet** [comment]
This was very usefull ! thanks
