### ISSUE TITLE
100*theta_s shooting bug

### ISSUE THREAD

**Issue by tbertolez** [lesgourg/class_public#598]
Hi,

I believe there is a bug (or something which I am not understanding) from the last committed CLASS versions. 
When asking `100*theta_s = 1.041783` (for instance), the shooting does not work well. 
In particular, it gives `h = 7.07077574575059930595e-01`, which I believe is not the right result. 

Furthermore, when CLASS picks this h value and computes the background and thermodynamics to compute 100*theta_s, it gives `100*theta_s = 1.050367`, which is not what I asked for. This leads to a very different cosmology.
I hope you can reproduce the bug (we have checked in different computers). v3.2.3 from the web works just fine.

Best!

**Comment by lesgourg** [comment]
Thanks! We are looking at this!

**Comment by lesgourg** [comment]
Hi @tbertolez , we indeed introduced a small bug in v3.2.4. We will correct it and push a new version 3.2.5 very quickly (1-2 days). In the meantime, you can fix this by just replacing abs() by fabs() in line 930 of source/input.c

**Comment by tbertolez** [comment]
Tested and seems to be working: wonderful! 
Thanks a lot for the quick answer, Julien.
Have a great day!
