### ISSUE TITLE
ImportError: No module named Cython.Distutils

### ISSUE THREAD

**Issue by rejapoci** [lesgourg/class_public#60]
I have been trying to install CLASS on Yosemite. Since 
`gcc --version`
gave me the clang version of gcc, I installed the GNU version using homebrew (or just brew, I am not sure of the difference). I got 

~~~
brew info gcc
gcc: stable 5.2.0 (bottled)
GNU compiler collection
https://gcc.gnu.org
/usr/local/Cellar/gcc/5.2.0 (1285 files, 215M)
  Built from source with: --without-multilib
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gcc.rb
==> Dependencies
Required: gmp ✔, libmpc ✔, mpfr ✔, isl ✔
==> Options
--with-all-languages
	Enable all compilers and languages, except Ada
--with-java
	Build the gcj compiler
--with-jit
	Build the jit compiler
--with-nls
	Build with native language support (localization)
--without-fortran
	Build without the gfortran compiler
--without-multilib
	Build without multilib support
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib
~~~

The last comment is a bit concerning. Should I rebuild it with `brew reinstall gcc --without-multilib`? I did not rebuild it, but I commented out the OMPFLAG in the class Makefile. 
My main problem now is that I cannot locate the gcc installed by homebrew. I thought it should be in /usr/local/Cellar/gcc/5.2.0, but there I can only find the following

~~~
[10:09 PM enricopajer:gcc] $ find ./ -name gcc*
.//5.2.0/bin/gcc-5
.//5.2.0/bin/gcc-ar-5
.//5.2.0/bin/gcc-nm-5
.//5.2.0/bin/gcc-ranlib-5
.//5.2.0/lib/gcc
.//5.2.0/lib/gcc/5/gcc
.//5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin14.5.0/5.2.0/plugin/include/ada/gcc-interface
.//5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin14.5.0/5.2.0/plugin/include/gcc-plugin.h
.//5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin14.5.0/5.2.0/plugin/include/gcc-symtab.h
.//5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin14.5.0/5.2.0/plugin/include/gcc.h
.//5.2.0/libexec/gcc
.//5.2.0/share/gcc-5.2.0
.//5.2.0/share/man/man1/gcc-5.1
~~~

So I tried to use the `gcc-5` (even though I don't know if it is the same as gcc). The Makefile ran, but I got the following error

~~~
...
a - build/hydrogen.o
a - build/history.o
cd python; export CC=gcc-5; python setup.py install 
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
make: *** [classy] Error 1
~~~

Any advice on any of these issue? I am happy with anything that gets class to run :)

Thanks,

Enrico

**Comment by ThomasTram** [comment]
Hi Enrico,

if you want to use OpenMP you should install without multilib as brew advises. (I think reinstall does not always work, so uninstall and do
````
brew install gcc --without-multilib
````
It will need to compile, so it will take maybe 10 minutes to complete. You will get gcc-5 as the binary which is completely fine. Then you just change your C-compiler to gcc-5 as you did and you can use OpenMP.

The other problem is because you do not have Cython installed: CLASS will work but the python wrapper will not. The best solution is to install Anaconda Python which has cython preinstalled.

Let me know haw it goes.

Cheers,
Thomas

**Comment by rejapoci** [comment]
Thomas,
Thanks for the quick reply. It worked indeed as you said. I had not realized that the cython complaint was about Python (I hadn't read the very well-written and useful installation documentation completely, sorry about that :( ). gcc-5 works indeed smoothly and I pip-ed cython and numpy which also did the trick.  Thanks again for the support,
best,

Enrico
