### ISSUE TITLE
Encountered an error while using ExoCLASS

### ISSUE THREAD

**Issue by Alaer0703** [lesgourg/class_public#601]
I installed ExoCLASS, and when I run ./DarkAgesModule/bin/DarkAges in the terminal, I encounter the following error.

(base) wang@wang-virtual-machine:~/ExoCLASS_perso-MergingExoCLASS$ ./DarkAgesModule/bin/DarkAges
#INFO: The transfer seem not to be initialized. This will be done now. this may take a few seconds.
#INFO: The transfer functions are now initialized and loaded.

Traceback (most recent call last):
  File "/home/wang/ExoCLASS_perso-MergingExoCLASS/./DarkAgesModule/bin/DarkAges", line 118, in <module>
    from DarkAges.__init__ import transfer_functions, get_logEnergies, set_logEnergies, get_redshift, DarkAgesError, print_info, set_background, get_background
  File "/home/wang/ExoCLASS_perso-MergingExoCLASS/DarkAgesModule/DarkAges/__init__.py", line 285, in <module>
    _transfer_load_from_dump()
  File "/home/wang/ExoCLASS_perso-MergingExoCLASS/DarkAgesModule/DarkAges/__init__.py", line 266, in _transfer_load_from_dump
    transfer_functions[idx] = transfer_load( os.path.join(os.environ['DARKAGES_BASE'], 'transfer_functions/transfer_Ch{:d}.obj'.format(idx+1)) )
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wang/ExoCLASS_perso-MergingExoCLASS/DarkAgesModule/DarkAges/transfer.py", line 110, in transfer_load
    raise DarkAgesError('The file {0} does not provide a proper instance of the class "transfer"'.format(infile))
DarkAges.__init__.DarkAgesError: 

!!! ERROR (DarkAgesError) !!!

 --> The file /home/wang/ExoCLASS_perso-MergingExoCLASS/DarkAgesModule/transfer_functions/transfer_Ch1.obj does not provide a proper instance of the class "transfer"

What is the reason for this?  Thank you for your help.

**Comment by alexander-reeves** [comment]
Hello, I am having the same issue- what was the fix here?
