### ISSUE TITLE
Multiple copies of class

### ISSUE THREAD

**Issue by DanBThomas** [lesgourg/class_public#62]
Hi

I currently have a gcc version of class working completely including the python wrapper.
I then made a 2nd (icc) version of class, which appeared to compile correctly (using the full make command) and I can run class directly with no problems.
However, when I tried to run montepython with this icc version of class, I got an error:
"You must have compiled the classy.pyx file. Please go to
/path/to/class/python and run the command
       python setup.py build"
I did this as requested, and there were no error messages. Nonetheless, I got the same error when I attempted to run montepython again.

I guess my question is, how does the python wrapper work for multiple copies of class?
In particular, is it possible to have two full copies of class (one gcc and one intel) including the python wrapper on a computer?

Thanks
Dan

**Comment by ThomasTram** [comment]
Hi,

first you should read this previous issue
https://github.com/lesgourg/class_public/issues/40
regarding having the wrapper working against an icc compiled CLASS library. Once you got this working, you can think about having two different CLASS wrappers installed simultaneously. Normally the python wrapper ````classy```` will be overwritten by the latest make command (however, better to do make clean to be certain.) You want to rename the wrapper module, so you gave to modify the python/setup.py script. Just change
````ext_modules=[Extension("classy", ["classy.pyx"],````
to for instance
````ext_modules=[Extension("classyicc", ["classy.pyx"],````
and change all
````from classy import Class````
statements to
````from classyicc import Class````
in the scripts of interest (eventually including MontePython). A much cleaner approach is probably to use ````virtualenv```` but I have no experience on this.

**Comment by ThomasTram** [comment]
Hi,

if you are using Anaconda Python (as recommended), you can use ````conda```` to create virtual python environments. 
````
conda create -n iccclassy --clone=/opt/apps/anaconda/2.2.0
source activate iccclassy
make clean; make -j
````
If you activate this environment and build classy afterwards, this version of classy will be installed in this environment. I am not entirely sure if the CLASS library file ````libclass.a```` is being copied to the python directory in this process, so it may be safer to have two different class folders, one for each environment.

Cheers,
Thomas
