### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Shunsuke-Fujii** [lesgourg/class_public#63]
I joined your seminor at Tokyo,Kavli IMPU.
I tried to download CLASS Tokyo version,which modified memory addressing for users of 32 bit virtualbox-ubuntu .

 Will you tell me how can I get Tokyo version?

Sincerely
 Shunsuke Fujii
(My former email address is 
  shun_z@hotmail.com
 or
 fujii@th.phys.titech.ac.jp)

**Comment by Shunsuke-Fujii** [comment]
I found the folder which I was looking for , at last. Sorry for tiny question.

Shunsuke Fujii

**Comment by ThomasTram** [comment]
Hi,

the bug we discovered in Tokyo has already been fixed in the newest public version. Did you encounter problems with the newest version...?

Cheers,
Thomas

**Comment by Shunsuke-Fujii** [comment]
Hi,Thomas.

It seemes that installing newest CLASS on CentOS run in 32-bit virtual box didn't work well.
It causes memory damp when I tried explanatory.ini as tried old version of Class on Ubuntu run in 32-bit virtual box.
  I guess modification of 32-bit memory adressing might not be reflected for 64-bit version of Newest Class code.
That's why I asked the former release class 4.3.1.  
  Do you agree about this point?

 Cheers,
  Shunsuke FUjii

**Comment by ThomasTram** [comment]
Hi Shunsuke,

I installed CentOS 32 bit on a virtual machine and reproduced the bug. It is a new bug not related to the one we fixed in Tokyo, and it is not even directly related to 32 bit. It is the same bug that gives rise to this issue:
https://github.com/lesgourg/class_public/issues/64
Please go to that issue for my follow up post, and thanks a lot for providing me with an easy way to reproduce the bug!

Cheers,
Thomas

**Comment by ThomasTram** [comment]
Hi again,

this issue should be fixed in the newest version. Can you please confirm that this is the case?

Thanks,
Thomas

**Comment by Shunsuke-Fujii** [comment]
Hi, Thomas.

Thank you so much ,Thomas. It works!

I reinstalled Newest version named 2.4(.4?) into Cent OS running on my 32 bit virtual box with
Cython in the python folder.

Then I use "make".

./class explamnatory.ini worked ,without having any error like I got before.

Thank you so much!!

Sincerely
 Shunsuke Fujii
