### ISSUE TITLE
Newest version freezes at Computing sources

### ISSUE THREAD

**Issue by santiagocasas** [lesgourg/class_public#64]
Hi all,

I had version 2.1.1. and everything was working perfectly.

Now with the latest version 2.4.3, using the same compiler and all the same flags, it compiles correctly but then when running the lcdm.ini, I get stuck at:

Computing background
 -> age = 13.461693 Gyr
 -> conformal age = 13894.100411 Mpc
Computing thermodynamics
 -> recombination at z = 1086.845754
    corresponding to conformal time = 278.779944 Mpc
    with comoving sound horizon = 142.281627 Mpc
    angular diameter distance = 12.515856 Mpc
    and sound horizon angle 100*theta_s = 1.045011
 -> baryon drag stops at z = 1064.691266
    corresponding to conformal time = 283.069659 Mpc
    with comoving sound horizon rs = 144.186978 Mpc
 -> reionization with optical depth = 0.084339
    corresponding to conformal time = 4458.125917 Mpc
Computing sources

After this I don't know if it ever finishes or not, but version 2.1.1 takes a couple of seconds, while this thing runs for more than a minute without any output.

**Comment by miguelzuma** [comment]
Hi Santi,

I run into a similar problem. In my case the code worked well when compiled with GCC 4.8, but had exactly your problem when compiled with GCC 4.9. You might want to check which version you are using or edit the compilation options in the makefile.

I could get around the problem in two different ways:

1) uncommenting the option -march=native in OPTFLAG. However, this caused a problem when running on the cluster on a node different from the one in which the code was compiled.

2) using an older version of GCC (in my case going back to 4.8.x) or ICC (for which you have to change other flags accordingly). Both options worked well, but I didn't manage to link the ICC version with Python.

**Comment by ThomasTram** [comment]
Hi,

it would be useful if you could list some details of your environments, such as CPU type, OS (and are you running in a virtual machine?), compiler flags and compiler, as well as ini file. However, going back to less agressive settings, -O2, no -ffast-math and no -march flag should always work.

Regarding ICC and the wrapper, it is possible to make it work. Please see this previous issue:
https://github.com/lesgourg/class_public/issues/40
Cheers,
Thomas

**Comment by santiagocasas** [comment]
Hi both,
Thanks @miguelzuma for the tips. I confirm your observations.

I start with the normal Makefile provided by the latest CLASS version here on github.

If I uncomment  -march=native, it works fine using gcc 4.9.

If I switch to gcc 4.8, then everything works fine, with the standard Makefile.

(Btw, I recommend the use of the tool 'update-alternatives' in Linux for these cases)

@ThomasTram I also confirm that if I use only -O2, then it works fine under gcc-4.9.

My OS is:
Linux  3.19.0-30-generic #34-Ubuntu x86_64 GNU/Linux

The ini file I am using is the lcdm.ini provided with the latest CLASS version.

CPU info is the following:
Quad core Intel Core i7-4720HQ (-HT-MCP-) cache: 6144 KB

Thanks!!

**Comment by ThomasTram** [comment]
Hi,

thanks to this issue
https://github.com/lesgourg/class_public/issues/63
I could reproduce the bug by running CLASS in 32 bit CentOS, and I tracked it down to this line in thermodynamics.c:
````chi_heat = MIN(0.996857*(1.-pow(1.-pow(preio->reionization_table[i*preio->re_size+preio->index_re_xe],0.300134),1.51035)),1);````
This can become complex (so NaN) for the last few values of the free electron fraction. Could you please try to see if changing back to the previous value
````chi_heat = (1.+2.*preio->reionization_table[i*preio->re_size+preio->index_re_xe])/3.;````
solves the problem?

The relation to -ffast-math is probably that it reshuffles the subsequent expressions to make them more vulnerable to this nan, thus allowing it to propagate.

Thanks,
Thomas

**Comment by ThomasTram** [comment]
Hi, this problem is solved in the newest version 2.4.4. Can you please check that this solves your problems?

Thanks,
Thomas

**Comment by santiagocasas** [comment]
Hi @ThomasTram , yes after cloning from github and using the standard Makefile with  the -ffast-math, I can see that the problem is solved.

**Comment by miguelzuma** [comment]
Hi Thomas, I also saw the problem with GCC 4.9 solved in the newest version. Thanks!

**Comment by ThomasTram** [comment]
Glad to hear that, I am closing the issue!
