### ISSUE TITLE
Installing Class on a Windows computer

### ISSUE THREAD

**Issue by YvetteWelling** [lesgourg/class_public#65]
Hi,

I have a problem with compiling Class on my Windows computer.
What I did so far is installing the basic set of packages from MinGW which provides a "GNU objective-C compiler" of version 4.8.1
Then when I type 'make clear' and after that 'make' in the terminal I get the following error message:

In file included from ../include/input.h:12:0,
                        from ../source.input.c:6:
../include/transer.h:8:21: fatal error: sys/shm.h: No such file or directory
 #include <sys/shm.h>
compilation terminated
make: *** [input.o] Error 1

Hopefully somebody can help me out what to do next.

**Comment by ThomasTram** [comment]
Hi Yvette,

you are lucky since the answer has been answered already. Try to have a look in this issue
https://github.com/lesgourg/class_public/issues/39
My last post give a complete recipe I think.

Cheers,

Thomas

**Comment by YvetteWelling** [comment]
Hi Thomas,

Thanks a lot for your quick reply and detailed description. 
Unfortunately I still get an error message after typing 'mingw32-make', namely:

   Makefile:8: *** multiple target patterns. Stop.

If the 8 refers to line 8 in the Makefile, it reads

    IF EXIST "$(WRKDIR)" (rd /s /q "$(WRKDIR)")

This is one of the lines I had to change in Makefile. Sorry for this question, but I am not familiar at all with the syntax, I hope you might be able to see immediately what goes wrong.

Cheers, Yvette

**Comment by ThomasTram** [comment]
I think you are missing a TAB character: All lines following a target (in this case .base) have to be TAB-indented. 
[MakefileWindows.txt](https://github.com/lesgourg/class_public/files/17730/MakefileWindows.txt)

I have uploaded the one I modified. (I can not guarantee that it works for you, but it might help anyway.)

Cheers,
Thomas
