### ISSUE TITLE
ultra relativistic species

### ISSUE THREAD

**Issue by lemiche** [lesgourg/class_public#66]
It is not clear if I consider the massive neutrino case, say 3 degenerate ones, so that I set the input parameters N_ncdm=1, m_ncdm=M_total (is that OK?), what should be modified in regards to the input parameter N_ur. And also in the output of the transfer functions, what does d_ur represent, once the mass of the neutrinos is turned on? Doesn't d_ur represent massless neutrinos?

**Comment by lemiche** [comment]
where are these treated in the code? where can I find documentation with more details on this issue?

**Comment by ThomasTram** [comment]
Hi,

you can find some information in the attached talk. If you want to have 3 degenerate massive neutrinos  (each with mass 0.06eV) and no massless species, you should use
````
N_ur = 0.0
N_ncdm = 1
m_ncdm = 0.06
deg_ncdm = 3.0
````
[lecture11_non_cold_dark_matter.pdf](https://github.com/lesgourg/class_public/files/19210/lecture11_non_cold_dark_matter.pdf)

In the transfer function output you will find a column for each *non-degenerate* ncdm species. In the case above there will be only 1. If ````N_ur=0.0```` there will not be any column with ur(=ultrarelativistic radiation). Note that depending on what you mean by M_total, it is not correct: m_ncdm is the actual mass of the eigenstate.

Cheers,
Thomas

**Comment by lemiche** [comment]
Thank you for the helpful reply :)
The "London hack days" slides course with the 
focus on NCDM were not detailed enough.
So thanks also for the attached talk!
