### ISSUE TITLE
Improving accuracy of matter power spectrum sensitivity to neutrino mass (precision settings)

### ISSUE THREAD

**Issue by aoifeboyle** [lesgourg/class_public#67]
Hello,

This will hopefully be an easy question for people familiar with the code. I am comparing matter power spectra output by CLASS with very small differences in the total neutrino mass (m_ncdm). The results are mostly good but I seem to get some very random numerical scattering from about k = 0.25 h/Mpc onwards when I compare two matter power spectra with slightly different neutrino masses (a difference of the order of 10^-5 eV). What precision parameters should I change to improve this? I can provide more details / some plots if necessary.

Thank you!

**Comment by ThomasTram** [comment]
Hi,

how big is the numerical scatter? The relevant accuracy settings and their default values are
````
tol_ncdm_synchronous = 1.e-3
tol_ncdm_newtonian = 1.e-5
tol_ncdm_bg = 1.e-5
l_max_ncdm=17
ncdm_fluid_trigger_tau_over_tau_k = 31.
ncdm_fluid_approximation = 2
````
My guess is that you can reduce the scatter in Pk by not using the ncdm_fluid_approximation, i.e. setting
````
ncdm_fluid_approximation = 3
````
However, even if this reduces the scatter, your result may still not have converged onto the *true* value. There is a reason for the fluid approximation after all... If you disable the fluid approximation, you should probably increase ````l_max_ncdm```` to 100 or 1000. You should also set 
````tol_ncdm_bg=1e-10```` and reduce ````tol_ncdm_synchronous````. Your code will be very slow at this point, but this is what you need if you want to do high precision tests. You may also want to study the CLASS papers as well as the precision files ````*.pre```` bundled with CLASS.

Cheers,
Thomas

**Comment by aoifeboyle** [comment]
Hi @ThomasTram. First of all, thank you so much for your reply. I spent the last few days trying out the parameters you suggested, and the scattering has been significantly reduced but not eliminated. I have attached a graph that shows two power spectra subtracted from each other, where one has a total neutrino mass that is 2.e-6 eV lower than that of the other. Here is my input file for one of these:

h = 0.697
Omega_b = 0.0461
Omega_cdm = 0.236
Omega_Lambda = 0.7179
output = mPk
P_k_max_h/Mpc = 0.35
z_pk = 4.0
k_per_decade_for_pk = 100
write warnings = yes
A_s = 2.43e-9
n_s = 0.9636
w0_fld = -1.073
wa_fld = 0.0
z_reio = 9.97
N_ncdm = 3
deg_ncdm = 1.0, 1.0, 1.0
N_ur = 0.00641
ncdm_fluid_approximation = 3
l_max_ncdm = 100
tol_ncdm_bg=1e-10
tol_ncdm_synchronous =1.e-5 
m_ncdm = 0.0007536, 0.0095, 0.0497434

Do you have any further suggestions? 

Thanks again,

Aoife

![difference](https://cloud.githubusercontent.com/assets/5586399/10733553/a5c6809c-7bff-11e5-9e1a-1f8f1fc982ab.png)

**Comment by ThomasTram** [comment]
Hi,

are we looking at Pk1(k)-Pk2(k) here? The more relevant quantity is the relative difference, 
1-Pk1(k)/Pk2(k). Assuming that what you plot is the difference, it means that the relative error is below 10^-5! This is below the accuracy threshold of P(k) even without neutrinos, and I think that new physical effects that is not taken into account would show up. (And linear perturbation theory is of course also not accurate enough.) A more basic problem is that interpolation error you introduce when comparing the two P(k) with different k samplings could be as big.

**Comment by aoifeboyle** [comment]
@ThomasTram You were right. I was going to use these results to calculate dPk/dm for the neutrino mass. I have increased the neutrino mass difference between the two spectra and that gives much more sensible results. Thank you for your help!
