### ISSUE TITLE
time dependence in transfer functions/denisty contrasts and in power spectrum 

### ISSUE THREAD

**Issue by lemiche** [lesgourg/class_public#71]
In the output for the power spectrum at a certain time,
is the growth function taken into account?
Same question for the transfer functions.
I am confused since in the output of the transfer functions,
you get a table that says these are the density contrasts.
So the question is do you get the full time dependent density contrast or just the
transfer function at a certain time, which you still have to multiply by the growth factor?

**Comment by ThomasTram** [comment]
Hi,

the headers in the transfer function (_tk) and the power spectrum (_pk) files read
````
#Transfer functions T_i(k) for adiabatic (AD) mode (normalized to initial curvature=1) at redshift z=0
# for k=1.04745e-05 to 1.00031 h/Mpc,
````

````
#Matter power spectrum P(k) at redshift z=0
# for k=1.04745e-05 to 1.00031 h/Mpc,
````

There is no such thing as a "growth function": the time evolution of a density contrast will in general depend on both wavemode k and type of species. You can get the matter power spectrum and transfer functions at various redshifts by specifying the input option ````z_pk```` as documented in ````explanatory.ini````:
````
3) value(s) 'z_pk' of redshift(s) for P(k,z) output file(s); can be ordered
   arbitrarily, but must be separated by comas (default: set 'z_pk' to 0)
z_pk = 0
#z_pk = 0., 1.2, 3.5
````

**Comment by lemiche** [comment]
Hi,

Following up on this issue I attach here a plot, where I show the ratio of the transfer functions of
the CDM component in a simple LambdaCDM universe at different times, taking its growth factor into account, where in a LambdaCDM universe the linear growth factor should in principle have NO k dependence. The plot shows that the ratio differs from 1varying across the k range, say of k=10^-3 to k=10^-1 by more than 1%, say 1.5%.

Could you please explain this unexpected k dependence, which deviates from the usual high precision standard expectation (1%)?

This deviation exactly entails a corresponding deviation of more than the 1% desirable accuracy in the results which I am interested at, and that is why it is important to me to be able to explain this additional k dependence. 

Thanks! 

![classinquiry](https://cloud.githubusercontent.com/assets/11328288/15269746/75e99514-1a09-11e6-9e68-fb4c2dd76e2e.jpeg)

**Comment by ThomasTram** [comment]
Have a look at https://github.com/lesgourg/class_public/issues/95
The small k scale dependence is due to radiation. At very large scales the deviation may be numerical and you would have to tune some precision settings.

Cheers,
Thomas
