### ISSUE TITLE
Error in the hydrogen recombination function?

### ISSUE THREAD

**Issue by vitenti** [lesgourg/class_public#74]
Hello!

It seems that the hydrogen H recombination rate is incorrect, it currently reads:

```
C = (1. + K*_Lambda_*n*(1.-x_H))/(1./preco->fu+K*_Lambda_*n*(1.-x)/preco->fu +K*Rup*n*(1.-x));
```

In the denominator it should be, if I'm not mistaken, (1.-x_H), i.e.,

```
C = (1. + K*_Lambda_*n*(1.-x_H))/(1./preco->fu+K*_Lambda_*n*(1.-x_H)/preco->fu +K*Rup*n*(1.-x_H));
```

In both Seager 1999 and recfast 1.5.2 the correct factor is (1.-x_H). Comparing with NumCosmo/NumCosmo integrator NcRecombSeager, using (1.-x) creates a ~10^{-2} error spike in X_e.

This typo is probably result from a similar typo in the definition of the `factor' variable in recfast, however, in recfast this variable is used nowhere.

**Comment by lesgourg** [comment]
This was corrected by a commit on Mar 26, 2016, but I forgot to thank you and close this issue!
