### ISSUE TITLE
How to add ncdm(non-cold dark matter) spieces??

### ISSUE THREAD

**Issue by ycbomeul** [lesgourg/class_public#78]
Hi,

I'm trying to obtain matter power spectrum including 3 degenerate massive neutrino. 

Thus in explanatory.ini input file, among the default values, I changed N_ncdm = 0 to N_cdm = 3 and #use_ncdm_psd_files =  to _ncdm_psd_files = 1 for using  pds_ FD_single.dat. 

But, after running this code i got error message like

SNU@207-05 ~/class
$ ./class explanatory.ini

Error running input_init_from_arguments
=>input_init_from_arguments(L:179) :error in input_init(&fc, ppr, pba, pth, ppt, ptr, ppm, psp, pnl, ple, pop, errmsg);
=>input_init(L:490) :error in input_read_parameters(pfc, ppr, pba, pth, ppt, ptr, ppm, psp, pnl, ple, pop, errmsg);
=>input_read_parameters(L:882) :condition (entries_read != N_ncdm) is true; Number of entries in use_ncdm_psd_files, 1, does not match expected number, 3.

I tried to understand what those this message means, but i couldn't.

Can someone help me getting through this??

**Comment by ThomasTram** [comment]
Hi

if you read the error message it says:
"Number of entries in use_ncdm_psd_files, 1, does not match expected number, 3."
It means that if you are using 3 NCDM species you should also provide a distribution function for all 3. However, you should *not* use this feature if you know the distribution function you want to use analytically. The default is to use Fermi-Dirac distributions for each species, optionally with different temperatures and chemical potentials. You may want to read this paper http://arxiv.org/abs/arXiv:1104.2935.

Cheers,
Thomas

**Comment by ycbomeul** [comment]
Thank your for the kind advise!!

I have one question about your comment Fermi-Dirac distributions for each species are default value. Does it mean that at explanatory.ini input file, i have to leave " #use_ncdm_psd_files = " unchanged?
When I set this " use_ncdm_psd_files = 0 ", and activate analytical form of p.s.d(default Fermi-Dirac) in corresponding bacground.c module, i got the same error message above.

**Comment by ThomasTram** [comment]
Yes, just leave " #use_ncdm_psd_files = " unchanged. It is equivalent to setting
````use_ncdm_psd_files = 0,0,0````
when ````N_ncdm = 3````. It is best to rely on the default behaviour, since otherwise you need to change the number of zeros every time you change N_ncdm.

Cheers,
Thomas

**Comment by ycbomeul** [comment]
I really appreciate your kind help!!
Thank you.
