### ISSUE TITLE
Adding sigma8 as an input parameter (=>class_fzero_ridder(L:3435) :error; root must be bracketed in zriddr.)

### ISSUE THREAD

**Issue by borisbolliet** [lesgourg/class_public#83]
Dear CLASS Users and Masters,

I am trying to add sigma8 as an input parameter. I have followed the method presented by  @ThomasTram at the CLASS Workshop in Barcelona. 

The compilation works fine. 

However, it seems the code gets stuck while trying to initialize sigma8 as I get the following error message:

///////////////////////////////////////////////////////////////////
_Error running input_init_from_arguments 
=>input_init_from_arguments(L:179) :error in input_init(&fc, ppr, pba, pth, ppt, ptr, ppm, psp, pnl, ple, pop, errmsg);
=>input_init(L:382) :error in class_fzero_ridder(input_fzerofun_1d, x1, x2, 1e-5*(((fabs(x1))<(fabs(x2))) ? (fabs(x2)) : (fabs(x1)) ), &fzw, &f1, &f2, &xzero, &fevals, errmsg);
**=>class_fzero_ridder(L:3435) :error; root must be bracketed in zriddr._**
///////////////////////////////////////////////////////////////

Did anyone encounter the same kind of issue before?
Does anyone know the solution to this problem? 

Thanks a lot,
CLASS is great.

Boris

**Comment by borisbolliet** [comment]
ISSUE CLOSED
I have got a modified version of CLASS with extra modules. On the original version I was able to add sigma8 as a new input parameter without any trouble, following the method presented by @ThomasTram during the worshop. 

In case anyone needs it, let me recall the steps to be done in order to add sigma8 as a new input parameter using the "shooting method".

- In **input.h**:
enum target_names {theta_s, Omega_dcdmdr, omega_dcdmdr, Omega_scf, Omega_ini_dcdm, omega_ini_dcdm,**tn_sigma8**};
enum computation_stage {cs_background, cs_thermodynamics, cs_perturbations,
                        cs_primordial, cs_nonlinear, cs_transfer, **cs_spectra**};
#define _NUM_TARGETS_ **7** //Keep this number as number of target_name

- In **input.c**:

1.  char * const target_namestrings[] = {"100*theta_s","Omega_dcdmdr","omega_dcdmdr",
                                       "Omega_scf","Omega_ini_dcdm","omega_ini_dcdm",****"sigma8"****};
  char * const unknown_namestrings[] = {"h","Omega_ini_dcdm","Omega_ini_dcdm",
                                        "scf_shooting_parameter","Omega_dcdmdr","omega_dcdmdr",****"A_s"***};

2. if (flag == _TRUE_)
    input_verbose = param;
  else
    input_verbose = 0;
// Optimise flags for sigma8 calculation.
**pt.k_max_for_pk=10.0;**
**pt.has_pk_matter=_TRUE_;**
**pt.has_perturbations = _TRUE_;**
**pt.has_cl_cmb_temperature = _FALSE_;**
**pt.has_cls = _FALSE_;**
**pt.has_cl_cmb_polarization = _FALSE_;**
**pt.has_cl_cmb_lensing_potential = _FALSE_;**
**pt.has_cl_number_count = _FALSE_;**
**pt.has_cl_lensing_potential=_FALSE_;**
**pt.has_density_transfers=_FALSE_;**
**pt.has_velocity_transfers=_FALSE_;**

3. switch (pfzw->target_name[i]) {
     **case tn_sigma8:**
       **output[i] = sp.sigma8 - pfzw->target_value[i];**
      **break;**
    case theta_s:

4. switch (pfzw->target_name[index_guess]) {
**case tn_sigma8:**
// Assume linear relationship between A_s and sigma8 and fix coefficient according to vanilla LambdaCDM. Should be good enough ...
**xguess[index_guess] = 2.43e-9/0.87659*pfzw->target_value[index_guess];**
**dxdy[index_guess] = 2.43e-9/0.87659;**
**break;**
    case theta_s

- Finally, in the "ini" file, specify the desired value for sigma8.

**Comment by borisbolliet** [comment]
CLOSED

**Comment by fkoehlin** [comment]
Hi Boris,

Many thanks for that recipe. I recently followed your steps to make sigma8 an input parameter (CLASS 2.5.0) and I just wanted to add that in point 1) one necessary change is missing:

// add cs_spectra here (this was missing in original post)
enum computation_stage target_cs[] = {cs_thermodynamics, cs_background, cs_background,
                                        cs_background, cs_background, cs_background, **cs_spectra**};

(Maybe that got mixed up with adding cs_spectra in "input.h" because in my case that entry was already there...)

Cheers,

Fabian

**Comment by mahtaparsa** [comment]
Dear Boris,
Thanks for your useful comment. However, I can not understand the last step "Finally, in the "ini" file, specify the desired value for sigma8" . How should I ask in the .ini file to print the sigma8 vs z file?

**Comment by borisbolliet** [comment]
Hi Fabian and Mahtaparsa,

Fabian: Thank you very much for your comment.

Mahtaparsa: 

You just need to specify, e.g. sigma8=0.8 in the **.ini file.

To get a file with sigma8 vs redshift you will need to modify two functions in "background.c":

1) int background_output_titles
2) int background_output_data

Then don't forget to set in the **.ini file:

write background = yes 

Let me know if you need further details,
Boris

**Comment by mahtaparsa** [comment]
Dear Boris, 
Thanks for your reply. Actually, I want to derive a relation for "f sigma8" in order to get an output file of it for my cosmological model. I need a file which contain "f sigma8" in term of redshift, in order to make a likelihood for "f sigma8" with the available observational data. First of all I should know the theory values of "f sigma8" predicted from my model. In background module there are relations for "f" and also "D". However, as I have understood they are for the LCDM model and have been defined from background parameters. I need their relations in the perturbation module (relations for "f" and "sigma8") in order to modify it according to my model. I do not think background module would be useful here.

**Comment by borisbolliet** [comment]
Yes, you are totally right.

Then, for a MG or DE model, the growth function "f" obeys a scale dependent differential equation that you have to implement in the perturbation module (the form of this equation depends on your model).

You have therefore to define a new variable, "f_de" for instance, in the perturbations.h file.

So, after you have done that, just do what I suggested in my previous post, but in the perturbation module (perturb_output_***).

Note that likelihood for "f*sigma8" given a MG or DE model is quite ambiguous, as I think the data  itself for "f*sigma8" is model dependent, it assumes LCDM (correct me if I am wrong).

Best,
Boris

**Comment by borisbolliet** [comment]
(you may want to have a look to this thread too: https://github.com/baudren/montepython_public/issues/93#issuecomment-310117877)

**Comment by mahtaparsa** [comment]
Dear Boris,
"f" measurements are according to LCDM  model. However, the "f sigma8" parameter is model-independent. You can see this paper arXiv:0807.0810v2  for more details.
