### ISSUE TITLE
Class did not read input parameter(s): w0_fld, cs2_fl, wa_fld

### ISSUE THREAD

**Issue by betalusso** [lesgourg/class_public#88]
I am new to montypython and I would like to run a modified version of base2015.param.
The experiments I have considered are:
data.experiments=['Planck_highl','Planck_lowl','hst','CFHTLens_correlation']
and I added the following three parameters to the parameter list:
data.parameters['cs2_fl']       = [1,         None, None,  0.016,    1, 'cosmo']
data.parameters['w0_fld']       = [-1,        None, None,  0.016,    1, 'cosmo']
data.parameters['wa_fld']       = [0,         None, None,  0.016,    1, 'cosmo']

I left anything else untouched, but unfortunately I have the following error
Cosmological Module Error:
 /|\   Something went wrong when calling CLASS
/_o_\  Error in Class: Class did not read input parameter(s): w0_fld, cs2_fl,
       wa_fld

I do not understand why w0 and wa are not recognised by CLASS. 
Any suggestion?
Thank you very much!

**Comment by ThomasTram** [comment]
Hi,

you must specify Omega_Lambda as well, or CLASS will not use a Dark Energy fluid. From explanatory.ini:
````
8a) Dark energy contributions. At least one out of three conditions must be satisfied:
    i)   'Omega_Lambda' unspecified.
    ii)  'Omega_fld' unspecified.
    iii) 'Omega_scf' set to a negative value. [Will be refered to as
         unspecified in the following text.]
    The code will then use the first unspecified component to satisfy the
    closure equation (sum_i Omega_i) equals (1 + Omega_k)
    (default: 'Omega_fld' and 'Omega_scf' set to 0 and 'Omega_Lambda' inferred
    by code)
````
What you want to do is probably to add 
data.cosmo_arguments['Omega_Lambda'] = 0.0
to your input file.

Cheers,
Thomas

**Comment by betalusso** [comment]
Thanks!

it worked only after having commented the following line
#data.parameters['cs2_fl']       = [1,         None, None,  0.016,    1, 'cosmo']

but I have now this issue
Error in Class: perturb_init(L:191) :condition (((pba->w0_fld + pba->wa_fld +1.0)*(pba->w0_fld+1.0)) < 0.0) is true; w crosses -1 between the infinite past and today, and this would lead to divergent perturbation equations for the fluid.


----------------------------------------------------------
Dr. Elisabeta Lusso
INAF-Osservatorio Astrofisico di Arcetri 
L.go E. Fermi 5 
50125 Firenze - Italy
tel: +39 055 2752 234
http://www.arcetri.astro.it/~lusso/Site/Home.html
----------------------------------------------------------

**Comment by ThomasTram** [comment]
Yes, that line had a spelling mistake, it should be cs2_fld not cs2_fl. Also you must set your priors in MontePython such that you do not cross w=-1. For instance 
0>=w0>=-1 and 0<=wa<=1
should work. (Just check the condition that CLASS prints in the error message.)
