### ISSUE TITLE
Plot some variables as a function of log k.

### ISSUE THREAD

**Issue by orjuelajavier** [lesgourg/class_public#89]
Hi, 
I am sorry if this is a trivial question, but I would like to know how I can plot the gravitational potentials(\phi, \psi) or velocities (photon, baryons,..) as a function of k at the time of last scattering for instance. I would be very grateful for your help.
Regards,
Javier.

**Comment by ThomasTram** [comment]
Hi,

you can add "dTk" and "vTk" to the "output=" of your .ini file (or your settings dictionary in Python). From explanatory.ini:
````
1.a) list of output spectra requested:
- 'tCl' for temperature Cls,
- 'pCl' for polarization Cls,
- 'lCl' for CMB lensing potential Cls,
- 'nCl' (or 'dCl') for density number count Cls,
- 'sCl' for galaxy lensing potential Cls,
- 'mPk' for total matter power spectrum P(k) infered from gravitational potential,
- 'dTk' (or 'mTk') for density transfer functions for each species,
- 'vTk' for velocity transfer function for each species.
By defaut, the code will try to compute the following cross-correlation Cls (if
available): temperature-polarisation, temperature-CMB lensing, polarization-CMB
lensing, and density-lensing. Other cross-correlations are not computed because
they would slow down the code considerably.

Can be left blank if you do not want to evolve cosmological perturbations at
all. (default: set to blanck, no perturbation calculation)

output = tCl,pCl,lCl,dTk,vTk,mPk
````
By default the transfer functions would be printed at z=0. However, you can print several at different redshifts by using
````
z_pk = 150.0, 100.0, 49.0, 10.0, 0.0
````
You control the maximum k by
````
P_k_max_1/Mpc =10.0
````
and you can increase the k resolution by increasing
````
k_per_decade_for_pk = 10
k_per_decade_for_bao = 70
````
Current limitations are that the earliest time you can request output is z~1000 by default and the transfer functions of the metric potentials are not (yet) output. The first limitation will be lifted in version 2.5 (arriving in a few days) and the second limitation can be tackled by using the total density and velocity transfer functions together with the Einstein equations which is a nice exercise. (Remember which gauge you are using.)

Cheers,
Thomas

**Comment by orjuelajavier** [comment]
Thanks so much for your answer  Thomas.
