### ISSUE TITLE
Large number of points for the power spectrum P(k)

### ISSUE THREAD

**Issue by MariaLuzdelSole** [lesgourg/class_public#91]
Hi,
I am starting to use CLASS. I am trying to run CLASS (./class myfile.ini cl_permille.pre) in order to get an output pk.dat (a file of P(k) and k), because I want to estimate the behaviour of the matter power spectrum in a WDM model with a non-cold dark matter species of mass 1 keV. My goal is to reproduce the black and blue curves of Fig.7 of http://arxiv.org/abs/1104.2935v3
Unfortunately, I cannot reproduce a nice WDM curve because I obtain an output with few points (~ 471 points), and I need much, much more points.
How could I run CLASS and obtain a LOT of points? 
Thank you very much in advance!!

**Comment by ThomasTram** [comment]
Hi,
the options you are looking for are 
````
P_k_max_1/Mpc = 1
k_per_decade_for_pk=100.
k_per_decade_for_bao=70.
````
However, the oscillations when the fluid approximation is turned off are not physical but due to numerical noise (I believe), contrary to our claim in 1104.2935. I have not found a way to eliminate them yet.

**Comment by MariaLuzdelSole** [comment]
Dear Thomas,

Thanks a lot for answering me. Thanks for your suggestions.

In case I find how to eliminate those oscillations, sure I let you know.

Best regards,

Roberta

2016-04-14 9:42 GMT+02:00 Thomas Tram <notifications@github.com>:
