### ISSUE TITLE
trg and 1-loop

### ISSUE THREAD

**Issue by changhoonhahn** [lesgourg/class_public#92]
I understand that TRG and 1-loop calculations for the non-linear matter power spectrum were dropped in the latest versions. Are there any branches or a simple way where I can still access them? 

Also, in the non-linear module [lecture note](http://lesgourg.web.cern.ch/lesgourg/class-tour/lecture6.pdf) on CLASS from 2014, it states that

> other fitting formulas, 
> restore one-loop PT,
> linking with recent codes of Scoccimarro et al., Bernardeau et al., Pietroni et al. featuring various renormalisation approaches

will be included in newer versions. Will those implementations be released soon?

**Comment by ThomasTram** [comment]
If you download the first GitHub release v2.0, you will find the files trg.c and trg_bispectrum.c. However I do not remember if trg was still working at this stage. Contrary to the lecture notes, there are no immediate plans on our side of implementing other fitting formulas. However, we would be happy to implement it if someone else makes a nice implementation of some quasi non-linear approach.
