### ISSUE TITLE
High precision settings for transfer functions 

### ISSUE THREAD

**Issue by lemiche** [lesgourg/class_public#96]
Hi,

Although I'm familiar with the CLASS slides course, and the sample pre. files in the CLASS directory, 
I cannot find clear info on how to set high precision for the transfer functions (e.g. as in CAMB).

Can you clarify what are the options\where can I find them?

Thanks!

**Comment by ThomasTram** [comment]
The transfer functions are already 'high precision'. Do you have some transfer function that seem to suffer from numerical inaccuracies? If you post a description and a plot maybe me or someone else can point to the set of parameters which have to be tuned.

It is impossible to have a single flag to directly improve the accuracy of all transfer functions: it will depend on the cosmological model, the species in question and the type of transfer function you are after. (Density or velocity.)

Cheers,
Thomas
