### ISSUE TITLE
"undefined symbol" error (classy)

### ISSUE THREAD

**Issue by fkoehlin** [lesgourg/class_public#99]
I'm currently trying to get CLASS' Python wrapper to run with Anaconda2 (4.0.0, Python 2.7.11) and everything seems to compile fine (modulo the usual warnings). However, when I try to test if classy was installed properly with "from classy import Class" I get the following error-message:

"/home/<username>/.local/lib/python2.7/site-packages/classy.so: undefined symbol: _ZGVbN2v_sin"

Scrolling a bit through some of previously reported similar issues seems to indicate that there might be a mismatch between the C-compilers used for compiling Class and other packages (NumPy!?). Can someone else confirm this or might have even a step-by-step workaround?

At least for me this issue is a bit recurring looking back to previous Class and Anaconda (or I guess equally Python) updates: sometimes everything works just out-of-the-box and sometimes it's producing an error-message similar to the above (the undefined symbol can vary...).

Any help/suggestions is very much appreciated!

**Comment by ThomasTram** [comment]
Hi,

which compiler do you use for compiling CLASS and what is your operating system? Normally if you use gcc to compile CLASS you should not have a problem.

Cheers,
Thomas

**Comment by fkoehlin** [comment]
Hi Thomas,

I'm on Ubuntu (16.04) and the compiler is gcc (5.3.1). As mentioned earlier I'm not always getting this error-message, some OS/Anaconda and Class versions just work out-of-the-box...

Cheers,

Fabian

**Comment by fkoehlin** [comment]
Hi Thomas,

Thanks for pushing me to the compiler version (it's so obvious that I forgot about it entirely...) I remembered one machine at work where everything worked about a month ago and there gcc-4.8.5 is installed (on Red Hat/ Fedora) but trying to set it up a couple of days ago on a colleague's machine with gcc-5.3.1 (again on Fedora/Red Hat) produced a similar "undefined symbol" error-message (different symbol, I think).
So, now I've installed gcc-4.8 on my Ubuntu (private laptop) and now classy works there again! So it seems to be due to gcc-5.3.1 for some reason...

Cheers,

Fabian

**Comment by ThomasTram** [comment]
I am glad I could help and that it is working now!

Cheers,
Thomas

**Comment by marius311** [comment]
I ran into this as well on Ubuntu 16.04 with gcc 5.3.1. For those not wishing to downgrade gcc, compiling CLASS with `-fno-tree-vectorize` seems to fix the problem as well. I don't notice any slow down of CLASS, granted I in no way did any exhaustive tests.

**Comment by santiagocasas** [comment]
Thanks marius311, that worked for me!!

**Comment by ThomasTram** [comment]
Hi

I stumbled upon this problem again today and pushed it a bit. It is not directly related to CLASS I believe. If you have the problem, try copying the following code testmvec.c
````
#include <math.h>
int main (){
  int N = 3200;
  double b[3200];
  double a[3200];
  int i;
  for (i = 0; i < N; i += 1)
    b[i] = sin (a[i]);
  return 0;
}
````
and compile it using:
````
gcc testmvec.c -O1 -ftree-loop-vectorize -ffast-math -lm -mavx
````
This reproduced the "undefined symbol" error on this system. Linking in the vector math library ````mvec```` explicitly solved the problem:
````
gcc testmvec.c -O1 -ftree-loop-vectorize -ffast-math -lmvec -lm -mavx
````
To get ````classy```` working I had to add ````mvec```` and the math library ````m```` explicitly in ````setup.py````:
````
libraries=["class","mvec","m"],
````
I will think about catching this error automatically in future versions. I think adding mvec permanently in the libraries part may break installations which do not have it installed, so it must be handled carefully. Any suggestions are welcome!

Cheers,
Thomas
